#!/usr/bin/env sh

[user]
  name = Frank Roeder
  useConfigOnly = true

[github]
  user = frankroeder

[status]
  showUntrackedFiles = all

[merge]
  tool = fugitive
  conflictstyle = merge

[mergetool "fugitive"]
  # http://vimcasts.org/episodes/fugitive-vim-resolving-merge-conflicts-with-vimdiff/
  cmd = $EDITOR -f -c \"Gvdiff!\" \"$MERGED\"

[mergetool]
  keepBackup = false

[diff]
  tool = vimdiff
  renames = copies

[pull]
  rebase = true

[push]
  followTags = true
  default = current

[core]
  editor = $EDITOR
  autocrlf = false
  filemode = false
  whitespace = fix,-indent-with-non-tab,trailing-space,cr-at-eol
  excludesfile = ~/.gitignore
  pager = less -XFR
  ignorecase = false
  attributesfile = ~/.dotfiles/git/gitattributes

[credential]
  helper = cache --timeout=3600 osxkeychain

[commit]
  template = ~/.dotfiles/git/gitmessage
  gpgsign = true

[credential "https://source.developers.google.com"]
  helper = gcloud.sh

[color]
  ui = true
  branch = auto
  diff = auto
  status = auto

[color "diff"]
  frag = magenta
  meta = yellow
  new = green
  old = red
  newMoved = cyan
  oldMoved = blue

[color "branch"]
  current = green bold
  local = yellow
  remote = blue

[color "status"]
  added = green reverse
  changed = yellow reverse
  untracked = red reverse

[color "grep"]
  match = yellow reverse
  filename = green
  function = blue
  linenumber = yellow

[init]
  defaultBranch = main

[include]
  path = "~/.local.gitconfig"
