tap "homebrew/cask-fonts"

brew "git"
brew "zsh"
brew "mas"
brew "htop"
brew "neovim"
brew "the_silver_searcher"
brew "wget"
brew "cmake"
brew "open-mpi"
brew "tree"
brew "llvm"
brew "libomp"
brew "tmux"
brew "node"
brew "tmux-mem-cpu-load"
brew "reattach-to-user-namespace"
brew "go"
brew "jq"
brew "python"
brew "pandoc"
brew "grip"
brew "gnuplot"
brew "ifstat"
brew "getantibody/tap/antibody"

cask "google-cloud-sdk"
cask "alfred"
cask "docker"
cask "alacritty"
cask "vlc"
cask "musescore"
cask "gpg-suite"
cask "skim"
cask "mactex-no-gui"
cask "font-hack-nerd-font"
cask "eloston-chromium"
cask "knockknock"

mas "iReal Pro", id: 409035833
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Wipr", id: 1320666476
mas "Magnet", id: 441258766
