tap "homebrew/cask-fonts"

brew "git"
brew "zsh"
brew "mas"
brew "htop"
brew "neovim"
brew "the_silver_searcher"
brew "wget"
brew "cmake"
brew "open-mpi"
brew "tree"
brew "llvm"
brew "libomp"
brew "tmux"
brew "node"
brew "go"
brew "jq"
brew "python"
brew "pandoc"
brew "grip"
brew "gnuplot"
brew "ifstat"
brew "getantibody/tap/antibody"
brew "gcc"

cask "google-cloud-sdk"
cask "alfred"
cask "docker"
cask "alacritty"
cask "vlc"
cask "musescore"
cask "gpg-suite"
cask "skim"
cask "mactex-no-gui"
cask "font-hack-nerd-font"
cask "firefox"
cask "rectangle"
cask "lulu"
cask "zoom"
cask "zotero"

mas "iReal Pro", id: 409035833
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "AdGuard", id: 1440147259
mas "Vimari", id: 1480933944
