#!/usr/bin/env sh

yabai -m config window_origin_display        default
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child

# floating windows are always on top
yabai -m config window_topmost               on
# show shadows only for floating windows
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity_duration      0.0

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          6

yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

# mouse
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off #autoraise
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# use shortcut to balance myself
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app='Bitwarden' manage=off
yabai -m rule --add app='Anki' manage=off
yabai -m rule --add app="^Calender$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^Podcasts$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m config external_bar all:15:0

echo "yabai configuration loaded..."
