#!/usr/bin/env sh

yabai -m config window_origin_display        default
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child

# floating windows are always on top
yabai -m config window_topmost               on
# show shadows only for floating windows
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off # NOTE: will be fixed
yabai -m config window_border_width          6

yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

# mouse
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off #autoraise
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# use shortcut to balance myself
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10
yabai -m config --space 2 top_padding        40

# window rules
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^(Dictionary|Music|Podcasts|App Store|Calender|Photos)$" manage=off

yabai -m rule --add app="^(Anki|Bitwarden)$" manage=off

echo "yabai configuration loaded..."
