#!/usr/bin/env bash
# Clear the icon cache
# Possible solution for invisible app icons

[[ $(uname -s) != 'Darwin' ]] && return

sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \;
sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} \;
sudo rm -rf /Library/Caches/com.apple.iconservices.store
killall Dock
