#!/usr/bin/env bash
# compress - archive wrapper
# usage: compress <foo.tar.gz> ./foo ./bar

if [[ -n "$1" ]]; then
  FILE=$1
  case $FILE in
    *.tar.bz2) shift && tar cjf "$FILE" "$*" ;;
    *.tar.gz) shift && tar czf "$FILE" "$*" ;;
    *.tgz) shift && tar czf "$FILE" "$*" ;;
    *.zip) shift && zip "$FILE" "$*" ;;
		*) echo "'$1' cannot be compressed";;
  esac
else
	echo "Usage:   compress <foo.tar.gz> ./foo ./bar"
	echo "Options: tar.bz2 tar.gz tgz zip"
fi
