#!/usr/bin/env zsh
# Move to macos trash

local path
declare -a files=()

for path in "$@"; do
  if [[ "$path" = -* ]]; then :
  else
    local dst=${path##*/}

    # Append the time if necessary
    while [ -e ~/.Trash/"$dst" ]; do
      dst="${dst}_${RANDOM}"
    done

    /bin/mv -fv "$path" ~/.Trash/"$dst"
    files+=("$dst")
  fi
done

export DEL_PWD=$(pwd)
export DEL_FILES=${files[@]}
