#!/usr/bin/env zsh
# Move to trash

local path
declare -a files=()

echo -n "Do you wish to move the following files to the trash $@ (y/n)? "
read answer
  if [ "$answer" != "${answer#[Yy]}" ]; then
      echo Yes

  for path in "$@"; do
    if [[ "$path" = -* ]]; then :
    else
      local dst=${path##*/}

      # Append the time if necessary
      while [ -e ~/.Trash/"$dst" ]; do
        dst="${dst}_${RANDOM}"
      done

      /bin/mv -fv "$path" ~/.Trash/"$dst"
      files+=("$dst")
    fi
  done

  export DEL_PWD=$(pwd)
  export DEL_FILES=${files[@]}
else
    echo "canceled..."
fi
