#!/usr/bin/env bash
# Empty the Trash on all mounted volumes and the main SSD/HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum

TRASH="$HOME/.Trash/*"
if [ "${#TRASH[@]}" -gt 0 ]; then
  for t in ~/.Trash/*; do sudo rm -rfv "$t"; done;
fi

if [ "$OSTYPE" = "Darwin" ]; then
  VOL_TRASH="/Volumes/*/.Trashes"
  if [ "${#VOL_TRASH[@]}" -gt 0 ] ; then
    sudo rm -rfv /Volumes/*/.Trashes;
  fi

  sudo rm -rfv /private/var/log/asl/*.asl;

  sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* \
    'delete from LSQuarantineEvent';
fi

if [ "$OSTYPE" = "Linux" ]; then
  sudo apt-get autoremove;
  sudo apt-get clean;
fi
