#!/usr/bin/env bash

# empty the main trash
local TRASH="$HOME/.Trash/*"
if [ "${#TRASH[@]}" -gt 0 ]; then
  for t in $HOME/.Trash/*; do
    sudo rm -rf "$t";
  done;
fi

pip cache purge;
conda clean --all -y;

if [ "$OSTYPE" = "Darwin" ]; then
  # remove the homewbrew cache
  rm -rf "$(brew --cache)";


  # empty the trashes on all mounted volumes
  local VOL_TRASH="/Volumes/*/.Trashes"
  if [ "${#VOL_TRASH[@]}" -gt 0 ] ; then
    sudo rm -rfv /Volumes/*/.Trashes;
  fi

  # clear system logs to improve shell startup speed
  sudo rm -rfv /private/var/log/asl/*.asl;

  # clear download history from quarantine. https://mths.be/bum
  sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* \
    'delete from LSQuarantineEvent';
elif [ "$OSTYPE" = "Linux" ]; then
  sudo apt autoclean -y;
  sudo apt clean -y;
  sudo apt autoremove -y;

  local THUMBNAIL_CACHE="$HOME/.cache/thumbnails";
  [[ -d $THUMBNAIL_CACHE ]] && rm -rfv "$THUMBNAIL_CACHE/*";
fi
