#!/usr/bin/env bash

if [ -f "$1" ] ; then
  local filename=$(basename "$1")
  local foldername="${filename%%.*}"
  local fullpath=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"`
  local didfolderexist=false

  if [ -d "$foldername" ]; then
    didfolderexist=true
    echo -n "$foldername already exists, do you want to overwrite it? (y/n) "
    read REPLY
    if [[ $REPLY =~ ^[Nn]$ ]]; then
      return
    fi
  fi

  case $1 in
    *.tar.bz2|*.tb2|*.tbz|*.tbz2) tar xjf "$fullpath" -C "$foldername" ;;
    *.tar.gz|*.tar.Z|*.taz|*.tgz) tar xzf "$fullpath" -C "$foldername" ;;
    *.tar.xz) tar Jxvf "$fullpath" -C "$foldername";;
    *.tar) tar xf "$fullpath" -C "$foldername" ;;
    *.txz) tar Jxvf "$fullpath"  -C "$foldername" ;;
    *.zip) unzip "$fullpath" -d "$foldername" ;;
    *.bz2) bunzip2 "$fullpath" > "$foldername" ;;
    *.gz) gunzip "$fullpath" > "$foldername" ;;
    *.xz) unxz "$fullpath" ;;
    *.Z) uncompress "$fullpath" ;;
    *) echo "'$1' cannot be extracted via extract()";;
  esac
else
  echo "'$1' is not a valid file"
fi
