#!/usr/bin/env bash

if [ -f "$1" ] ; then
  local filename=$(basename "$1")
  local foldername="${filename%%.*}"
  local fullpath=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"`
  local didfolderexist=false

  if [ -d "$foldername" ]; then
    didfolderexist=true
    echo -n "$foldername already exists, do you want to overwrite it? (y/n) "
    read REPLY
    if [[ $REPLY =~ ^[Nn]$ ]]; then
      return
    fi
  fi

  case $1 in
    *.tar.bz2) tar xjf "$fullpath" ;;
    *.tar.gz) tar xzf "$fullpath" ;;
    *.tar.xz) tar Jxvf "$fullpath" ;;
    *.tar.Z) tar xzf "$fullpath" ;;
    *.tar) tar xf "$fullpath" ;;
    *.taz) tar xzf "$fullpath" ;;
    *.tb2) tar xjf "$fullpath" ;;
    *.tbz) tar xjf "$fullpath" ;;
    *.tbz2) tar xjf "$fullpath" ;;
    *.tgz) tar xzf "$fullpath" ;;
    *.txz) tar Jxvf "$fullpath" ;;
    *.zip) unzip "$fullpath" ;;
    *.bz2) bunzip2 "$fullpath" ;;
    *.gz) gunzip "$fullpath";;
    *) echo "'$1' cannot be extracted via extract()";;
  esac
else
  echo "'$1' is not a valid file"
fi
