#!/usr/bin/env bash

if [[ -f "$1" ]]; then
	case "$1" in
		*.tar.bz2) tar xvjf "$1";;
		*.tar.gz) tar xvzf "$1";;
		*.tar.xz) tar xvJf "$1";;
		*.tar.lzma) tar --lzma xvf "$1";;
		*.bz2) bunzip "$1";;
		*.rar) unrar "$1";;
		*.gz) gunzip "$1";;
		*.tar) tar xvf "$1";;
		*.tbz2) tar xvjf "$1";;
		*.tgz) tar xvzf "$1";;
		*.zip) unzip "$1";;
		*.Z) uncompress "$1";;
		*.7z) 7z x "$1";;
		*.dmg) hdiutul mount "$1";; # mount OS X disk images
		*) echo "'$1' cannot be extracted";;
esac
else
	echo "'$1' is not a valid file"
fi
