#!/usr/bin/env zsh

git log --graph --color=always \
    --format="%C(auto)%h%d %s %C(black)%C(yellow)%cr" "$@" |
fzf --ansi +s --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
    --bind "ctrl-m:execute:
              (grep -o '[a-f0-9]\{7\}' | head -1 |
              xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
              {}
FZF-EOF"
