#!/usr/bin/env zsh
# Open or edit a file with ctrl-o or ctrl-e

local out file key
local IFS=$'\n' out=($(fzf-tmux --query="$1" --exit-0 --no-mouse \
  --header 'Press C-e to edit or C-o to open (default)' --sort \
  --expect=ctrl-o,ctrl-e))

key=$(head -1 <<< "$out")
file=$(head -2 <<< "$out" | tail -1)

if [[ -n "$file" ]]; then
  [[ "$key" == ctrl-e ]] &&  ${EDITOR:-vim} "$file" || open "$file"
fi
