#!/usr/bin/env bash
# Show how much RAM application uses.
# Usage: ram safari

APP="$1"
if [ -z "$APP" ]; then
  echo "First argument - pattern to grep from processes"
else
  SUM=0
  for i in `ps aux | grep -i "$APP" | grep -v "grep" | awk '{print $6}'`; do
    SUM=$(($i + $SUM))
  done
  SUM=$(echo "scale=2; $SUM / 1024.0" | bc)
  if [[ $SUM != "0" ]]; then
    printf "${BLUE}${APP}${RESET} uses ${GREEN}${SUM}${RESET} MBs of RAM."
  else
    printf "There are no processes with pattern '${BLUE}${APP}${RESET}' are running."
  fi
fi
