#!/usr/bin/env bash

sudo rm -rfv /Library/Caches/com.apple.iconservices.store
sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \;
sudo find /Applications -type f -name 'Info.plist' -maxdepth 4 -exec touch {} +
killall Dock; killall Finder
