#!/usr/bin/env zsh
# generate a random string/password

# @raycast.title Random Password
# @raycast.author Frank Röder
# @raycast.authorURL https://github.com/frankroeder
# @raycast.description Generate a random password of specified length
#
# @raycast.icon 🔐
# @raycast.argument1 { "type": "text", "placeholder": "length"}
# @raycast.mode compact
# @raycast.refreshTime 3m
# @raycast.packageName Developer Utils
# @raycast.schemaVersion 1

LC_ALL=C tr -dc "[:alnum:]" < /dev/urandom | head -c ${1-64};
