#!/usr/bin/env bash

usage ()
{
    echo "Reduces PDF filesize by lossy recompressing with Ghostscript."
    echo "quality options: 'screen', 'ebook' or 'prepress'"
    echo "Usage: shrinkpdf file.pdf <option>"
}

echo_sizes() {
  if [ ! -f "$1" -o ! -f "$2" ]; then
    return 0;
  fi
  echo "Input file size $(($(stat -f "%z" $1) / 1000)) kB"
  echo "Ouput file size $(($(stat -f "%z" $2) / 1000)) kB"
}

if [ -z "$1" ]; then
    usage "$0"
else
  local QUALITY="${2-ebook}"
  local INPUT_FILE="$1"

  local FNAME=$(basename "$1")
  local OUTPUT_FILE="${FNAME%.*}-small.${FNAME#*.}"

  ${HOMEBREW_PREFIX}/bin/gs \
    -sDEVICE=pdfwrite \
    -dCompatibilityLevel=1.4 \
    -dPDFSETTINGS=/"$QUALITY" \
    -dNOPAUSE \
    -dQUIET \
    -dBATCH \
    -dEmbedAllFonts=true \
    -dSubsetFonts=true \
	  -dAutoRotatePages=/None \
    -sOutputFile="$OUTPUT_FILE" "$INPUT_FILE"

  echo_sizes $INPUT_FILE $OUTPUT_FILE
fi
