#!/usr/bin/env bash

usage ()
{
    echo "Reduces PDF filesize by lossy recompressing with Ghostscript."
    echp "quality options: 'screen', 'ebook' or 'prepress'"
    echo "Usage: shrinkpdf ebook file.pdf"
}

if [ -z "$1" ]; then
    usage "$0"
else
  local QUALITY="${2-ebook}"
  local INPUT_FILE="$1"
  local FNAME=$(basename "$1")
  local OUTPUT_FILE="${FNAME%.*}_small.${FNAME#*.}"

  /usr/local/bin/gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4  -dPDFSETTINGS=/"$QUALITY" -dNOPAUSE \
    -dQUIET -dBATCH -sOutputFile="$OUTPUT_FILE" "$INPUT_FILE"
fi
