#!/usr/bin/env bash
# Make ZSH the default shell environment

if [[ "$(uname)" = "Darwin" ]] && ! fgrep -q "$(brew --prefix)/bin/zsh" /etc/shells
then
  echo "$(brew --prefix)/bin/zsh" | sudo tee -a /etc/shells
elif ! fgrep -q "/usr/bin/zsh" /etc/shells
then
	echo $(which zsh) | sudo tee -a /etc/shells
fi

if [[ "$(uname)" = "Darwin" ]]
then
  chsh -s "$(brew --prefix)/bin/zsh"
elif [[ "$(uname)" = "Darwin" ]]
then
  chsh -s "$(command -v zsh)"
fi
