#!/usr/bin/env bash
# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# some directories, listing directories first.

local ignore=$(paste -d\| -s "$DOTFILES/ignore")

if [ -z "${1}" ]; then
  tree -aC -I $ignore --dirsfirst "$@";
else
  tree -aC -I $ignore -L "$1";
fi
