#!/usr/bin/env bash
# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# some directories, listing directories first.

ignore='.git|node_modules|venv|__pycache__'

if [ -z "${1}" ]; then
  tree -aC -I $ignore --dirsfirst "$@";
else
  tree -aC -I $ignore -L "$1";
fi
