#!/bin/bash

success() {
  printf "\\r[ ${GREEN}\\u2713${RESET} ] %s\\n" "${1}"
}

error() {
  printf "\\r[ ${RED}\\u274C${RESET} ] %s\\n" "${1}"
}

in_progress() {
  printf "${YELLOW}Starting${RESET} %s\\n" "${1}"
}

exec_update() {
  in_progress "${1}"

  start_time=$(date +%s)

  if $1; then
    end_time=$(date +%s)
    total_time="$(( end_time - start_time ))"
    success "${1} in ${total_time} seconds"
  else
    error "${1}"
  fi
}

brew_update() {
  brew update;
  brew upgrade --display-times;
  brew cask upgrade;
  brew cleanup -s && rm -rfv "$(brew --cache)";
}

pip_update() {
  pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  \
    | xargs -n1 pip install -U --user --no-warn-script-location;
  pip install --upgrade pip;
  }

antibody_update() {
  antibody update;
  antibody bundle < "$DOTFILES/antibody/bundles.txt" > ~/.zsh/zsh_plugins.sh;
}

npm_update() {
  npm install npm -g;
  npm update -g;
}

gem_update() {
  gem update --system;
  gem update;
  gem cleanup;
  sudo gem update --system;
  sudo gem update;
  sudo gem cleanup;
}

macos_update() {
  sudo softwareupdate -i -a --restart;
}

neovim_plug_update() {
  nvim +PlugUpgrade +PlugInstall +PlugClean! +PlugUpdate +qall!
}

mas_update() {
  mas upgrade
}

if ping -c 1 google.com &> /dev/null; then
  echo -e "$BLUE########################"
  printf "# Checking for updates #\n"
  echo -e "########################$RESET\n"

  exec_update brew_update
  exec_update pip_update
  exec_update neovim_plug_update
  exec_update gem_update
  exec_update antibody_update
  exec_update mas_update
  exec_update macos_update

  success "Updates completed"
else
  error "No internet access"
fi
