#!/usr/bin/env bash

success() {
  printf "\\r[ ${GREEN}\\u2713${RESET} ] %s\\n" "${1}"
}

error() {
  printf "\\r[ ${RED}\\u274C${RESET} ] %s\\n" "${1}"
}

in_progress() {
  printf "${YELLOW}Starting${RESET} %s\\n" "${1}"
}

exec_update() {
  in_progress "${1}"

  start_time=$(date +%s)

  if $1; then
    end_time=$(date +%s)
    total_time="$(( end_time - start_time ))"
    success "${1} in ${total_time} seconds"
  else
    error "${1}"
  fi
}

brew_update() {
  brew update;
  brew upgrade --display-times;
  brew upgrade --cask;
  brew cleanup -s && rm -rfv "$(brew --cache)";
}

pip_update() {
  python3 -m pip install --upgrade setuptools;
  python3 -m pip install --upgrade pip;
  python3 -m pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 python3 -m pip install -U;
}

antibody_update() {
  antibody update;
  antibody bundle < "$DOTFILES/antibody/bundles.txt" > ~/.zsh/zsh_plugins.sh;
}

npm_update() {
  npm install npm@latest -g;
  npm update -g;
}

gem_update() {
  sudo gem update --system;
  sudo gem update;
  sudo gem cleanup;
}

macos_update() {
  sudo softwareupdate -i -a --restart;
}

neovim_plug_update() {
  nvim -E +PlugUpgrade +PlugInstall +PlugClean! +PlugUpdate +qall!;
}

mas_update() {
  mas upgrade;
}

apt_update() {
  sudo apt update -y;
  sudo apt upgrade -y;
}

run(){
  if ping -c 1 google.com &> /dev/null; then
    echo -e "$BLUE########################"
    printf "# Checking for updates #\n"
    echo -e "########################$RESET\n"

    sudo -v
    # Keep-alive: update existing `sudo` time stamp until script has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

    [ $commands[python3] ] && exec_update pip_update
    [ $commands[nvim] ] && exec_update neovim_plug_update
    [ $commands[antibody] ] && exec_update antibody_update
    [ $commands[npm] ] && exec_update npm_update
    [ $commands[gem] ] && exec_update gem_update
    [ $commands[mas] ] && exec_update mas_update
    [ $commands[brew] ] && exec_update brew_update
    [ "$OSTYPE" = "Darwin" ] &&  exec_update macos_update
    [ "$OSTYPE" = "Linux" ] && exec_update apt_update

    success "Updates completed"
  else
    error "No internet access"
  fi
}
run;
