#!/bin/zsh

UPGRADE_PIP=0

# Deactivate any existing virtualenv
if [ "$VIRTUAL_ENV" ]; then
  if [ "$(command -v deactivate)" ]; then
    echo "Deactivating $VIRTUAL_ENV..."
    deactivate
  else
    unset VIRTUAL_ENV;
  fi
fi

# By default, pick $(pwd) as the new env
target=$(pwd)
target=${target:1}

# Use first argument instead if it exists
if [ -n "$1" ]; then
  target="$1"
fi

# If the first argument is '-', just quit - ie, only deactivate
if [ "$target" = "-" ]; then
  return
fi

# If the $target doesn't exist in the current dir, use ~/envs/$(target)
if [ ! -f "${target}/bin/activate" ]; then
  target=~/envs/"$target"
fi

# Make the env if it doesn't exist
if [ ! -f "${target}/bin/activate" ]; then
  echo "Creating ${target}"
  mkdir -p "$target"
  python -m venv "$target"
  UPGRADE_PIP=1
fi

# Activate the env
echo "Activating ${target}"
source "${target}/bin/activate"

if [[ $UPGRADE_PIP == 1 ]]; then
  pip install --upgrade pip
fi
