#!/usr/bin/env sh

# Export the BAR_NAME to be used by the lua module
export BAR_NAME=sketchybar
export CONFIG_DIR="$HOME/.config/sketchybar"

# Execute the init.lua script
exec lua $CONFIG_DIR/init.lua