"""Write theme artifacts and apply them live to the Asahi desktop stack."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

from .palette import Palette

STATE_DIR_NAME = "asahi-theme"


def state_dir() -> Path:
    xdg = os.environ.get("XDG_STATE_HOME")
    base = Path(xdg) if xdg else Path.home() / ".local" / "state"
    path = base / STATE_DIR_NAME
    path.mkdir(parents=True, exist_ok=True)
    return path


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _hex_rgb(hx: str) -> str:
    return hx.lstrip("#")


def write_colors_json(p: Palette, path: Path) -> None:
    _atomic_write(path, json.dumps(p.to_dict(), indent=2, sort_keys=True) + "\n")


def write_colors_toml(p: Palette, path: Path) -> None:
    content = f"""mode = "{p.mode}"

accent = "{p.accent}"
selection = "{p.selection}"
muted = "{p.muted}"

background = "{p.background}"
dark_background = "{p.dark_background}"
darker_background = "{p.darker_background}"
lighter_background = "{p.lighter_background}"

foreground = "{p.foreground}"
dark_foreground = "{p.dark_foreground}"
light_foreground = "{p.light_foreground}"
bright_foreground = "{p.bright_foreground}"

red = "{p.red}"
yellow = "{p.yellow}"
orange = "{p.orange}"
green = "{p.green}"
cyan = "{p.cyan}"
blue = "{p.blue}"
magenta = "{p.magenta}"
brown = "{p.brown}"

bright_red = "{p.bright_red}"
bright_yellow = "{p.bright_yellow}"
bright_green = "{p.bright_green}"
bright_cyan = "{p.bright_cyan}"
bright_blue = "{p.bright_blue}"
bright_magenta = "{p.bright_magenta}"
"""
    _atomic_write(path, content)


def write_ghostty_theme(p: Palette, path: Path) -> None:
    content = f"""# Generated by asahi-autotheme from wallpaper
background = {p.background}
foreground = {p.foreground}
cursor-color = {p.accent}
cursor-text = {p.background}
selection-background = {p.selection}
selection-foreground = {p.foreground}
palette = 0={p.surface1}
palette = 1={p.red}
palette = 2={p.green}
palette = 3={p.yellow}
palette = 4={p.blue}
palette = 5={p.magenta}
palette = 6={p.cyan}
palette = 7={p.subtext1}
palette = 8={p.surface2}
palette = 9={p.bright_red}
palette = 10={p.bright_green}
palette = 11={p.bright_yellow}
palette = 12={p.bright_blue}
palette = 13={p.bright_magenta}
palette = 14={p.bright_cyan}
palette = 15={p.bright_foreground}
"""
    _atomic_write(path, content)


def write_ghostty_gtk_css(p: Palette, path: Path) -> None:
    # Ghostty ignores Adw StyleManager on reload-config (#13127); CSS is the live path.
    bg, fg = p.background, p.foreground
    surface, accent = p.surface0, p.accent
    sel = p.selection
    content = f"""/* Generated by asahi-autotheme */
@define-color asahi_bg {bg};
@define-color asahi_fg {fg};
@define-color asahi_surface {surface};
@define-color asahi_accent {accent};
@define-color asahi_sel {sel};

@define-color window_bg_color {bg};
@define-color window_fg_color {fg};
@define-color view_bg_color {bg};
@define-color view_fg_color {fg};
@define-color headerbar_bg_color {bg};
@define-color headerbar_fg_color {fg};
@define-color headerbar_backdrop_color {bg};
@define-color headerbar_shade_color {surface};
@define-color sidebar_bg_color {bg};
@define-color sidebar_fg_color {fg};
@define-color secondary_sidebar_bg_color {surface};
@define-color dialog_bg_color {bg};
@define-color dialog_fg_color {fg};
@define-color popover_bg_color {surface};
@define-color popover_fg_color {fg};
@define-color card_bg_color {surface};
@define-color card_fg_color {fg};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {bg};
@define-color destructive_bg_color {p.red};
@define-color shade_color {surface};

window, .background {{
  background-color: {bg};
  color: {fg};
}}

headerbar,
.titlebar,
tabbar,
adw-tab-bar,
.adw-tab-bar {{
  background-color: {bg};
  color: {fg};
}}

headerbar button,
tabbar button,
adw-tab-bar button {{
  color: {fg};
}}

adw-dialog,
.dialog-vbox,
window.dialog,
window.popup {{
  background-color: {bg};
  color: {fg};
}}

entry, searchbar, textview {{
  background-color: {surface};
  color: {fg};
  caret-color: {fg};
}}

list, listview, columnview {{
  background-color: {bg};
  color: {fg};
}}

row:selected, .card:selected {{
  background-color: {sel};
  color: {fg};
}}
"""
    _atomic_write(path, content)


def write_ghostty_extra(p: Palette, path: Path, css_name: str = "adaptive.css") -> None:
    content = f"""# Generated by asahi-autotheme
window-theme = ghostty
window-titlebar-background = {p.background}
window-titlebar-foreground = {p.foreground}
gtk-custom-css = ?{css_name}
"""
    _atomic_write(path, content)


def write_hyprland_lua(p: Palette, path: Path) -> None:
    active = _hex_rgb(p.accent)
    secondary = _hex_rgb(p.mauve)
    inactive = _hex_rgb(p.surface1)
    text = _hex_rgb(p.text)
    muted = _hex_rgb(p.subtext0)
    base = _hex_rgb(p.base)
    content = f"""-- Generated by asahi-autotheme
hl.config({{
  general = {{
    ["col.active_border"] = {{ colors = {{ "rgb({active})", "rgb({secondary})" }}, angle = 45 }},
    ["col.inactive_border"] = "rgb({inactive})",
  }},
  group = {{
    ["col.border_active"] = {{ colors = {{ "rgb({active})", "rgb({secondary})" }}, angle = 45 }},
    ["col.border_inactive"] = "rgb({inactive})",
    groupbar = {{
      text_color = "rgb({text})",
      text_color_inactive = "rgba({muted}90)",
      col = {{
        active = "rgba({base}dd)",
        inactive = "rgba({base}88)",
      }},
    }},
  }},
}})
"""
    _atomic_write(path, content)


def write_hyprlock_conf(p: Palette, path: Path) -> None:
    bg = _hex_rgb(p.background)
    fg = _hex_rgb(p.foreground)
    accent = _hex_rgb(p.accent)
    muted = _hex_rgb(p.subtext0)
    ok = _hex_rgb(p.green)
    fail = _hex_rgb(p.red)
    shadow = _hex_rgb(p.crust)
    mauve = _hex_rgb(p.mauve)
    teal = _hex_rgb(p.teal)
    maroon = _hex_rgb(p.maroon)
    content = f"""# Generated by asahi-autotheme
$lock_bg = rgb({bg})
$lock_fg = rgb({fg})
$lock_accent = rgb({accent})
$lock_muted = rgb({muted})
$lock_ok = rgb({ok})
$lock_fail = rgb({fail})
$lock_shadow = rgba({shadow}cc)
$lock_outer = rgba({accent}ee) rgba({mauve}ee) 45deg
$lock_check = rgba({ok}ee) rgba({teal}ee) 120deg
$lock_fail_grad = rgba({fail}ee) rgba({maroon}ee) 40deg
"""
    _atomic_write(path, content)


def write_gtk_css(p: Palette, path: Path) -> None:
    content = f"""/* Generated by asahi-autotheme */
@define-color window_bg_color {p.background};
@define-color window_fg_color {p.foreground};
@define-color view_bg_color {p.background};
@define-color view_fg_color {p.foreground};
@define-color headerbar_bg_color {p.background};
@define-color headerbar_fg_color {p.foreground};
@define-color headerbar_backdrop_color {p.background};
@define-color headerbar_shade_color {p.surface0};
@define-color sidebar_bg_color {p.background};
@define-color sidebar_fg_color {p.foreground};
@define-color secondary_sidebar_bg_color {p.surface0};
@define-color dialog_bg_color {p.background};
@define-color dialog_fg_color {p.foreground};
@define-color popover_bg_color {p.surface0};
@define-color popover_fg_color {p.foreground};
@define-color card_bg_color {p.surface0};
@define-color card_fg_color {p.foreground};
@define-color accent_bg_color {p.accent};
@define-color accent_fg_color {p.background};
@define-color accent_color {p.accent};
@define-color destructive_bg_color {p.red};
@define-color shade_color {p.surface0};
"""
    _atomic_write(path, content)


def write_chromium_policy(p: Palette, path: Path) -> None:
    _atomic_write(path, json.dumps({"BrowserThemeColor": p.background}, indent=2) + "\n")


def write_librewolf_css(p: Palette, path: Path) -> None:
    content = f"""/* Generated by asahi-autotheme */
:root {{
  color-scheme: {p.mode} !important;
  --asahi-bg: {p.base};
  --asahi-bg-alt: {p.mantle};
  --asahi-surface: {p.surface0};
  --asahi-surface-alt: {p.surface1};
  --asahi-fg: {p.text};
  --asahi-accent: {p.accent};
  --asahi-border: {p.surface1};

  --toolbar-bgcolor: var(--asahi-bg) !important;
  --toolbar-color: var(--asahi-fg) !important;
  --toolbarbutton-icon-fill: var(--asahi-fg) !important;
  --toolbarbutton-hover-background: var(--asahi-surface) !important;
  --toolbarbutton-active-background: var(--asahi-surface-alt) !important;
  --lwt-accent-color: var(--asahi-bg) !important;
  --lwt-accent-color-inactive: var(--asahi-bg-alt) !important;
  --lwt-text-color: var(--asahi-fg) !important;
  --lwt-toolbar-field-background-color: var(--asahi-surface) !important;
  --lwt-toolbar-field-color: var(--asahi-fg) !important;
  --lwt-toolbar-field-border-color: var(--asahi-border) !important;
  --lwt-selected-tab-background-color: var(--asahi-surface) !important;
  --tab-selected-bgcolor: var(--asahi-surface) !important;
  --tab-selected-color: var(--asahi-fg) !important;
  --urlbar-box-bgcolor: var(--asahi-surface) !important;
  --urlbar-box-text-color: var(--asahi-fg) !important;
  --urlbarView-highlight-background: var(--asahi-surface-alt) !important;
  --urlbarView-highlight-color: var(--asahi-fg) !important;
  --arrowpanel-background: var(--asahi-bg-alt) !important;
  --arrowpanel-color: var(--asahi-fg) !important;
  --arrowpanel-border-color: var(--asahi-border) !important;
  --sidebar-background-color: var(--asahi-bg) !important;
  --sidebar-text-color: var(--asahi-fg) !important;
}}

#navigator-toolbox,
#sidebar-main,
#sidebar-box {{
  background-color: var(--asahi-bg) !important;
  color: var(--asahi-fg) !important;
}}

#navigator-toolbox {{
  border-bottom: 1px solid var(--asahi-border) !important;
}}

#urlbar-background,
#searchbar {{
  background-color: var(--asahi-surface) !important;
  border-color: var(--asahi-border) !important;
}}

#urlbar[focused] #urlbar-background {{
  border-color: var(--asahi-accent) !important;
}}

.tab-background[selected],
.tabbrowser-tab:not([selected]):hover .tab-background {{
  background-color: var(--asahi-surface) !important;
}}

menupopup,
panel {{
  --panel-background: var(--asahi-bg-alt) !important;
  --panel-color: var(--asahi-fg) !important;
  --panel-border-color: var(--asahi-border) !important;
}}
"""
    _atomic_write(path, content)


def install_ghostty_theme(theme_file: Path) -> Path | None:
    candidates = [
        Path.home() / ".config" / "ghostty" / "themes",
        Path.home() / ".dotfiles" / "asahi" / "ghostty" / "themes",
    ]
    for themes in candidates:
        if themes.parent.exists() or themes.exists():
            themes.mkdir(parents=True, exist_ok=True)
            dest = themes / "asahi-adaptive"
            shutil.copy2(theme_file, dest)
            return dest
    return None


def install_librewolf_css(css_file: Path) -> list[Path]:
    roots = [
        Path.home() / ".config" / "librewolf" / "librewolf",
        Path.home() / ".librewolf",
    ]
    written: list[Path] = []
    for root in roots:
        if not root.is_dir():
            continue
        for profile in root.glob("*.default*"):
            chrome = profile / "chrome"
            chrome.mkdir(parents=True, exist_ok=True)
            dest = chrome / "asahi-adaptive.css"
            shutil.copy2(css_file, dest)
            written.append(dest)
    return written


def apply_hyprland_live(p: Palette) -> None:
    if not shutil.which("hyprctl"):
        return
    active = _hex_rgb(p.accent)
    secondary = _hex_rgb(p.mauve)
    inactive = _hex_rgb(p.surface1)
    text = _hex_rgb(p.text)
    muted = _hex_rgb(p.subtext0)
    base = _hex_rgb(p.base)
    # hyprctl keyword is rejected by the lua provider; eval applies borders live.
    lua = (
        "hl.config({ general = { "
        f'["col.active_border"] = {{ colors = {{ "rgb({active})", "rgb({secondary})" }}, angle = 45 }}, '
        f'["col.inactive_border"] = "rgb({inactive})" '
        "}, group = { "
        f'["col.border_active"] = {{ colors = {{ "rgb({active})", "rgb({secondary})" }}, angle = 45 }}, '
        f'["col.border_inactive"] = "rgb({inactive})", '
        "groupbar = { "
        f'text_color = "rgb({text})", '
        f'text_color_inactive = "rgba({muted}90)", '
        f'col = {{ active = "rgba({base}dd)", inactive = "rgba({base}88)" }} '
        "} } })"
    )
    subprocess.run(["hyprctl", "eval", lua], check=False, capture_output=True)


def install_gtk_css(css_file: Path) -> list[Path]:
    written: list[Path] = []
    import_line = '@import url("asahi-adaptive.css");\n'
    for ver in ("gtk-3.0", "gtk-4.0"):
        dest_dir = Path.home() / ".config" / ver
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / "asahi-adaptive.css"
        shutil.copy2(css_file, dest)
        written.append(dest)
        gtk_css = dest_dir / "gtk.css"
        if gtk_css.is_symlink():
            gtk_css.unlink()
        existing = gtk_css.read_text(encoding="utf-8") if gtk_css.is_file() else ""
        if "asahi-adaptive.css" not in existing:
            _atomic_write(gtk_css, import_line + existing)
    return written


def install_chromium_policy(policy_file: Path) -> list[Path]:
    written: list[Path] = []
    roots = [
        Path.home() / ".config" / "chromium" / "policies" / "managed",
        Path.home() / ".config" / "chromium-browser" / "policies" / "managed",
    ]
    for root in roots:
        # Prefer chromium; only create chromium-browser policy if that tree exists.
        parent = root.parent.parent
        if not parent.is_dir() and "chromium-browser" in str(root):
            continue
        root.mkdir(parents=True, exist_ok=True)
        dest = root / "asahi-theme.json"
        shutil.copy2(policy_file, dest)
        written.append(dest)
    return written


def apply_chromium_live() -> None:
    binary = shutil.which("chromium-browser") or shutil.which("chromium")
    if not binary:
        return
    running = subprocess.run(
        ["pgrep", "-x", "chromium"], check=False, capture_output=True
    )
    if running.returncode != 0:
        running = subprocess.run(
            ["pgrep", "-x", "chromium-browser"], check=False, capture_output=True
        )
    if running.returncode != 0:
        return
    subprocess.run(
        [binary, "--refresh-platform-policy", "--no-startup-window"],
        check=False,
        capture_output=True,
    )


def apply_gsettings(p: Palette) -> None:
    if not shutil.which("gsettings"):
        return
    scheme = "prefer-dark" if p.mode == "dark" else "prefer-light"
    gtk = "adw-gtk3-dark" if p.mode == "dark" else "adw-gtk3"
    icons = "Papirus-Dark" if p.mode == "dark" else "Papirus"
    subprocess.run(
        ["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", scheme],
        check=False,
        capture_output=True,
    )
    subprocess.run(
        ["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", gtk],
        check=False,
        capture_output=True,
    )
    subprocess.run(
        ["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", icons],
        check=False,
        capture_output=True,
    )


def reload_ghostty() -> None:
    if not shutil.which("gdbus"):
        return
    subprocess.run(
        [
            "gdbus",
            "call",
            "--session",
            "--dest",
            "com.mitchellh.ghostty",
            "--object-path",
            "/com/mitchellh/ghostty",
            "--method",
            "org.gtk.Actions.Activate",
            "reload-config",
            "[]",
            "{}",
        ],
        check=False,
        capture_output=True,
    )


def write_colors_env(p: Palette, path: Path) -> None:
    content = f"""# Generated by asahi-autotheme
export CATPPUCCIN_TERM_MODE="{p.mode}"
export CATPPUCCIN_TERM_BACKGROUND="{p.background}"
export CATPPUCCIN_TERM_FOREGROUND="{p.foreground}"
export CATPPUCCIN_TERM_SELECTION_BG="{p.selection}"
export CATPPUCCIN_TERM_CURSOR="{p.accent}"
export CATPPUCCIN_TERM_BLACK="{p.surface1}"
export CATPPUCCIN_TERM_RED="{p.red}"
export CATPPUCCIN_TERM_GREEN="{p.green}"
export CATPPUCCIN_TERM_YELLOW="{p.yellow}"
export CATPPUCCIN_TERM_BLUE="{p.blue}"
export CATPPUCCIN_TERM_MAGENTA="{p.magenta}"
export CATPPUCCIN_TERM_CYAN="{p.cyan}"
export CATPPUCCIN_TERM_WHITE="{p.subtext1}"
export CATPPUCCIN_TERM_BRIGHT_BLACK="{p.surface2}"
export CATPPUCCIN_TERM_BRIGHT_RED="{p.bright_red}"
export CATPPUCCIN_TERM_BRIGHT_GREEN="{p.bright_green}"
export CATPPUCCIN_TERM_BRIGHT_YELLOW="{p.bright_yellow}"
export CATPPUCCIN_TERM_BRIGHT_BLUE="{p.bright_blue}"
export CATPPUCCIN_TERM_BRIGHT_MAGENTA="{p.bright_magenta}"
export CATPPUCCIN_TERM_BRIGHT_CYAN="{p.bright_cyan}"
export CATPPUCCIN_TERM_BRIGHT_WHITE="{p.bright_foreground}"
"""
    _atomic_write(path, content)


def write_screensaver_toml(p: Palette, path: Path) -> None:
    content = (
        f'background = "{p.background}"\n'
        f'foreground = "{p.foreground}"\n'
        f'color4 = "{p.blue}"\n'
        f'color1 = "{p.red}"\n'
        f'accent = "{p.accent}"\n'
    )
    _atomic_write(path, content)


def bump_theme_marker(path: Path, name: str = "wallpaper") -> None:
    import time

    _atomic_write(path, f"{name}-{int(time.time())}\n")


def apply_gtk_settings(p: Palette) -> None:
    prefer = "0" if p.mode == "light" else "1"
    gtk = "adw-gtk3" if p.mode == "light" else "adw-gtk3-dark"
    icons = "Papirus" if p.mode == "light" else "Papirus-Dark"
    body = (
        "[Settings]\n"
        f"gtk-application-prefer-dark-theme={prefer}\n"
        f"gtk-theme-name={gtk}\n"
        f"gtk-icon-theme-name={icons}\n"
        "gtk-cursor-theme-size=24\n"
    )
    for ver in ("gtk-3.0", "gtk-4.0"):
        path = Path.home() / ".config" / ver / "settings.ini"
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        _atomic_write(path, body)


def write_all(p: Palette) -> dict[str, Path]:
    root = state_dir()
    ghostty_cfg = Path.home() / ".config" / "ghostty"
    # Prefer writing next to the live Ghostty config (Asahi symlink → repo).
    if not ghostty_cfg.exists():
        ghostty_cfg = Path.home() / ".dotfiles" / "asahi" / "ghostty"
    adaptive_conf = ghostty_cfg / "adaptive.conf"
    adaptive_css = ghostty_cfg / "adaptive.css"

    paths = {
        "colors_json": root / "colors.json",
        "colors_toml": root / "colors.toml",
        "ghostty": root / "ghostty.theme",
        "ghostty_extra": adaptive_conf,
        "ghostty_css": adaptive_css,
        "hyprland": root / "hyprland.lua",
        "hyprlock": root / "hyprlock.conf",
        "librewolf": root / "librewolf.css",
        "gtk_css": root / "gtk.css",
        "chromium": root / "chromium-theme.json",
        "wallpaper": root / "wallpaper",
        "screensaver": root / "screensaver-colors.toml",
        "theme_name": root / "theme.name",
        "colors_env": root / "colors.env",
    }
    write_colors_json(p, paths["colors_json"])
    write_colors_toml(p, paths["colors_toml"])
    write_colors_env(p, paths["colors_env"])
    write_ghostty_theme(p, paths["ghostty"])
    write_ghostty_gtk_css(p, paths["ghostty_css"])
    write_ghostty_extra(p, paths["ghostty_extra"], css_name=adaptive_css.name)
    write_hyprland_lua(p, paths["hyprland"])
    write_hyprlock_conf(p, paths["hyprlock"])
    write_librewolf_css(p, paths["librewolf"])
    write_gtk_css(p, paths["gtk_css"])
    write_chromium_policy(p, paths["chromium"])
    write_screensaver_toml(p, paths["screensaver"])
    _atomic_write(paths["wallpaper"], p.wallpaper + "\n")
    install_ghostty_theme(paths["ghostty"])
    install_librewolf_css(paths["librewolf"])
    install_gtk_css(paths["gtk_css"])
    install_chromium_policy(paths["chromium"])
    # Bump last so FileView watchers reload after all artifacts exist.
    bump_theme_marker(paths["theme_name"], Path(p.wallpaper).stem or "wallpaper")
    return paths


def apply_live(p: Palette) -> None:
    apply_gtk_settings(p)
    apply_hyprland_live(p)
    apply_gsettings(p)
    apply_chromium_live()
    reload_ghostty()
