# spaceship
SPACESHIP_PROMPT_DEFAULT_PREFIX=""
SPACESHIP_USER_SHOW=false

SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_COLOR=yellow
SPACESHIP_DIR_TRUNC_REPO=false

SPACESHIP_BATTERY_SHOW=false

SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_SYMBOL=""
SPACESHIP_GIT_BRANCH_SUFFIX=""
SPACESHIP_GIT_BRANCH_COLOR=green

SPACESHIP_DOCKER_PREFIX=""
SPACESHIP_DOCKER_COLOR=blue
SPACESHIP_DOCKER_SYMBOL="🐳  "

SPACESHIP_PACKAGE_SHOW=false

SPACESHIP_VENV_SYMBOL="🐍  "

SPACESHIP_KUBECONTEXT_PREFIX=""
SPACESHIP_KUBECONTEXT_SHOW=true
