// Emoji browse + search for the remix launcher.
// Conservative ES2018 — QML JS and node tests both load this file.

var EMOJI = [
  { g: "😀", n: "grinning face", k: "smile happy" },
  { g: "😃", n: "grinning face with big eyes", k: "smile happy" },
  { g: "😄", n: "grinning face with smiling eyes", k: "smile happy" },
  { g: "😁", n: "beaming face with smiling eyes", k: "smile grin" },
  { g: "😆", n: "grinning squinting face", k: "laugh" },
  { g: "😅", n: "grinning face with sweat", k: "relief nervous" },
  { g: "🤣", n: "rolling on the floor laughing", k: "lol rofl" },
  { g: "😂", n: "face with tears of joy", k: "lol laugh cry" },
  { g: "🙂", n: "slightly smiling face", k: "smile" },
  { g: "🙃", n: "upside-down face", k: "sarcasm" },
  { g: "😉", n: "winking face", k: "wink" },
  { g: "😊", n: "smiling face with smiling eyes", k: "blush happy" },
  { g: "😇", n: "smiling face with halo", k: "angel innocent" },
  { g: "🥰", n: "smiling face with hearts", k: "love" },
  { g: "😍", n: "smiling face with heart-eyes", k: "love crush" },
  { g: "🤩", n: "star-struck", k: "star eyes wow" },
  { g: "😘", n: "face blowing a kiss", k: "kiss love" },
  { g: "😗", n: "kissing face", k: "kiss" },
  { g: "😚", n: "kissing face with closed eyes", k: "kiss" },
  { g: "😋", n: "face savoring food", k: "yum tasty" },
  { g: "😛", n: "face with tongue", k: "tongue" },
  { g: "😜", n: "winking face with tongue", k: "wink joke" },
  { g: "🤪", n: "zany face", k: "goofy" },
  { g: "😝", n: "squinting face with tongue", k: "tongue" },
  { g: "🤗", n: "smiling face with open hands", k: "hug" },
  { g: "🤭", n: "face with hand over mouth", k: "oops secret" },
  { g: "🤫", n: "shushing face", k: "quiet secret" },
  { g: "🤔", n: "thinking face", k: "think hmm" },
  { g: "🫡", n: "saluting face", k: "salute yes" },
  { g: "🤐", n: "zipper-mouth face", k: "silent" },
  { g: "🤨", n: "face with raised eyebrow", k: "skeptical" },
  { g: "😐", n: "neutral face", k: "meh" },
  { g: "😑", n: "expressionless face", k: "blank" },
  { g: "😶", n: "face without mouth", k: "silent" },
  { g: "😏", n: "smirking face", k: "smirk" },
  { g: "😒", n: "unamused face", k: "meh annoyed" },
  { g: "🙄", n: "face with rolling eyes", k: "eyeroll" },
  { g: "😬", n: "grimacing face", k: "awkward" },
  { g: "😮‍💨", n: "face exhaling", k: "sigh relief" },
  { g: "🤥", n: "lying face", k: "lie pinocchio" },
  { g: "😌", n: "relieved face", k: "relief calm" },
  { g: "😔", n: "pensive face", k: "sad" },
  { g: "😪", n: "sleepy face", k: "tired" },
  { g: "🤤", n: "drooling face", k: "hungry" },
  { g: "😴", n: "sleeping face", k: "sleep zzz" },
  { g: "😷", n: "face with medical mask", k: "sick mask" },
  { g: "🤒", n: "face with thermometer", k: "sick fever" },
  { g: "🤕", n: "face with head-bandage", k: "hurt" },
  { g: "🤢", n: "nauseated face", k: "sick vomit" },
  { g: "🤮", n: "face vomiting", k: "sick vomit" },
  { g: "🥵", n: "hot face", k: "heat" },
  { g: "🥶", n: "cold face", k: "freeze" },
  { g: "🥴", n: "woozy face", k: "drunk dizzy" },
  { g: "😵", n: "face with crossed-out eyes", k: "dizzy" },
  { g: "🤯", n: "exploding head", k: "mind blown" },
  { g: "🤠", n: "cowboy hat face", k: "cowboy" },
  { g: "🥳", n: "partying face", k: "party celebrate" },
  { g: "😎", n: "smiling face with sunglasses", k: "cool" },
  { g: "🤓", n: "nerd face", k: "geek nerd" },
  { g: "🧐", n: "face with monocle", k: "inspect" },
  { g: "😕", n: "confused face", k: "confused" },
  { g: "😟", n: "worried face", k: "worry" },
  { g: "🙁", n: "slightly frowning face", k: "sad" },
  { g: "☹️", n: "frowning face", k: "sad" },
  { g: "😮", n: "face with open mouth", k: "surprise" },
  { g: "😯", n: "hushed face", k: "wow" },
  { g: "😲", n: "astonished face", k: "shock" },
  { g: "😳", n: "flushed face", k: "embarrassed" },
  { g: "🥺", n: "pleading face", k: "please puppy" },
  { g: "🥹", n: "face holding back tears", k: "emotional" },
  { g: "😢", n: "crying face", k: "sad tear" },
  { g: "😭", n: "loudly crying face", k: "sob cry" },
  { g: "😤", n: "face with steam from nose", k: "angry huff" },
  { g: "😠", n: "angry face", k: "mad" },
  { g: "😡", n: "pouting face", k: "rage mad" },
  { g: "🤬", n: "face with symbols on mouth", k: "swear" },
  { g: "😈", n: "smiling face with horns", k: "devil" },
  { g: "👿", n: "angry face with horns", k: "devil" },
  { g: "💀", n: "skull", k: "dead" },
  { g: "☠️", n: "skull and crossbones", k: "dead pirate" },
  { g: "💩", n: "pile of poo", k: "poop" },
  { g: "🤡", n: "clown face", k: "clown" },
  { g: "👻", n: "ghost", k: "halloween" },
  { g: "👽", n: "alien", k: "ufo" },
  { g: "👾", n: "alien monster", k: "game" },
  { g: "🤖", n: "robot", k: "bot" },
  { g: "😺", n: "grinning cat", k: "cat smile" },
  { g: "😸", n: "grinning cat with smiling eyes", k: "cat" },
  { g: "😹", n: "cat with tears of joy", k: "cat lol" },
  { g: "😻", n: "smiling cat with heart-eyes", k: "cat love" },
  { g: "😼", n: "cat with wry smile", k: "cat smirk" },
  { g: "😽", n: "kissing cat", k: "cat kiss" },
  { g: "🙀", n: "weary cat", k: "cat shock" },
  { g: "😿", n: "crying cat", k: "cat sad" },
  { g: "😾", n: "pouting cat", k: "cat angry" },
  { g: "🙈", n: "see-no-evil monkey", k: "monkey hide" },
  { g: "🙉", n: "hear-no-evil monkey", k: "monkey" },
  { g: "🙊", n: "speak-no-evil monkey", k: "monkey quiet" },
  { g: "👋", n: "waving hand", k: "wave hello bye" },
  { g: "🤚", n: "raised back of hand", k: "stop" },
  { g: "✋", n: "raised hand", k: "stop high five" },
  { g: "🖖", n: "vulcan salute", k: "spock" },
  { g: "👌", n: "ok hand", k: "ok" },
  { g: "🤌", n: "pinched fingers", k: "italian" },
  { g: "✌️", n: "victory hand", k: "peace" },
  { g: "🤞", n: "crossed fingers", k: "luck" },
  { g: "🤟", n: "love-you gesture", k: "love" },
  { g: "🤘", n: "sign of the horns", k: "rock metal" },
  { g: "🤙", n: "call me hand", k: "shaka" },
  { g: "👈", n: "backhand index pointing left", k: "left" },
  { g: "👉", n: "backhand index pointing right", k: "right" },
  { g: "👆", n: "backhand index pointing up", k: "up" },
  { g: "👇", n: "backhand index pointing down", k: "down" },
  { g: "☝️", n: "index pointing up", k: "up" },
  { g: "👍", n: "thumbs up", k: "yes like +1" },
  { g: "👎", n: "thumbs down", k: "no dislike" },
  { g: "✊", n: "raised fist", k: "power" },
  { g: "👊", n: "oncoming fist", k: "punch" },
  { g: "👏", n: "clapping hands", k: "bravo clap" },
  { g: "🙌", n: "raising hands", k: "hooray" },
  { g: "🫶", n: "heart hands", k: "love" },
  { g: "👐", n: "open hands", k: "open" },
  { g: "🤲", n: "palms up together", k: "pray offer" },
  { g: "🤝", n: "handshake", k: "deal agree" },
  { g: "🙏", n: "folded hands", k: "please thanks pray" },
  { g: "💪", n: "flexed biceps", k: "strong muscle" },
  { g: "👀", n: "eyes", k: "look see" },
  { g: "👁️", n: "eye", k: "see" },
  { g: "👅", n: "tongue", k: "tongue" },
  { g: "👄", n: "mouth", k: "lips" },
  { g: "💋", n: "kiss mark", k: "kiss" },
  { g: "🧠", n: "brain", k: "smart" },
  { g: "❤️", n: "red heart", k: "love heart" },
  { g: "🧡", n: "orange heart", k: "love" },
  { g: "💛", n: "yellow heart", k: "love" },
  { g: "💚", n: "green heart", k: "love" },
  { g: "💙", n: "blue heart", k: "love" },
  { g: "💜", n: "purple heart", k: "love" },
  { g: "🖤", n: "black heart", k: "love" },
  { g: "🤍", n: "white heart", k: "love" },
  { g: "🤎", n: "brown heart", k: "love" },
  { g: "💔", n: "broken heart", k: "heartbreak" },
  { g: "💕", n: "two hearts", k: "love" },
  { g: "💞", n: "revolving hearts", k: "love" },
  { g: "💓", n: "beating heart", k: "love" },
  { g: "💗", n: "growing heart", k: "love" },
  { g: "💖", n: "sparkling heart", k: "love" },
  { g: "💘", n: "heart with arrow", k: "cupid" },
  { g: "💝", n: "heart with ribbon", k: "gift love" },
  { g: "✨", n: "sparkles", k: "shine stars" },
  { g: "⭐", n: "star", k: "star" },
  { g: "🌟", n: "glowing star", k: "star" },
  { g: "💫", n: "dizzy", k: "spark" },
  { g: "🔥", n: "fire", k: "hot lit" },
  { g: "💥", n: "collision", k: "boom" },
  { g: "💯", n: "hundred points", k: "100 perfect" },
  { g: "✅", n: "check mark button", k: "done yes ok" },
  { g: "❌", n: "cross mark", k: "no x" },
  { g: "❓", n: "red question mark", k: "question" },
  { g: "❗", n: "red exclamation mark", k: "bang" },
  { g: "⚠️", n: "warning", k: "caution" },
  { g: "🚫", n: "prohibited", k: "no stop" },
  { g: "🐶", n: "dog face", k: "dog puppy" },
  { g: "🐱", n: "cat face", k: "cat kitten" },
  { g: "🐭", n: "mouse face", k: "mouse" },
  { g: "🐹", n: "hamster", k: "hamster" },
  { g: "🐰", n: "rabbit face", k: "bunny" },
  { g: "🦊", n: "fox", k: "fox" },
  { g: "🐻", n: "bear", k: "bear" },
  { g: "🐼", n: "panda", k: "panda" },
  { g: "🐨", n: "koala", k: "koala" },
  { g: "🐯", n: "tiger face", k: "tiger" },
  { g: "🦁", n: "lion", k: "lion" },
  { g: "🐮", n: "cow face", k: "cow" },
  { g: "🐷", n: "pig face", k: "pig" },
  { g: "🐸", n: "frog", k: "frog" },
  { g: "🐵", n: "monkey face", k: "monkey" },
  { g: "🐔", n: "chicken", k: "chicken" },
  { g: "🐧", n: "penguin", k: "penguin" },
  { g: "🐦", n: "bird", k: "bird" },
  { g: "🐤", n: "baby chick", k: "chick" },
  { g: "🦆", n: "duck", k: "duck" },
  { g: "🦅", n: "eagle", k: "eagle" },
  { g: "🦉", n: "owl", k: "owl" },
  { g: "🦇", n: "bat", k: "bat" },
  { g: "🐺", n: "wolf", k: "wolf" },
  { g: "🐗", n: "boar", k: "boar" },
  { g: "🐴", n: "horse face", k: "horse" },
  { g: "🦄", n: "unicorn", k: "unicorn" },
  { g: "🐝", n: "honeybee", k: "bee" },
  { g: "🐛", n: "bug", k: "bug" },
  { g: "🦋", n: "butterfly", k: "butterfly" },
  { g: "🐌", n: "snail", k: "snail" },
  { g: "🐞", n: "lady beetle", k: "ladybug" },
  { g: "🐢", n: "turtle", k: "turtle" },
  { g: "🐍", n: "snake", k: "snake" },
  { g: "🐙", n: "octopus", k: "octopus" },
  { g: "🦑", n: "squid", k: "squid" },
  { g: "🦀", n: "crab", k: "crab" },
  { g: "🐠", n: "tropical fish", k: "fish" },
  { g: "🐟", n: "fish", k: "fish" },
  { g: "🐬", n: "dolphin", k: "dolphin" },
  { g: "🐳", n: "spouting whale", k: "whale" },
  { g: "🐋", n: "whale", k: "whale" },
  { g: "🦈", n: "shark", k: "shark" },
  { g: "🌸", n: "cherry blossom", k: "flower sakura" },
  { g: "💮", n: "white flower", k: "flower" },
  { g: "🏵️", n: "rosette", k: "flower" },
  { g: "🌹", n: "rose", k: "flower love" },
  { g: "🥀", n: "wilted flower", k: "flower" },
  { g: "🌺", n: "hibiscus", k: "flower" },
  { g: "🌻", n: "sunflower", k: "flower" },
  { g: "🌼", n: "blossom", k: "flower" },
  { g: "🌷", n: "tulip", k: "flower" },
  { g: "🌱", n: "seedling", k: "plant grow" },
  { g: "🌲", n: "evergreen tree", k: "tree" },
  { g: "🌳", n: "deciduous tree", k: "tree" },
  { g: "🌴", n: "palm tree", k: "tree beach" },
  { g: "🌵", n: "cactus", k: "cactus" },
  { g: "🍀", n: "four leaf clover", k: "luck" },
  { g: "🍁", n: "maple leaf", k: "autumn" },
  { g: "🍂", n: "fallen leaf", k: "autumn" },
  { g: "🍃", n: "leaf fluttering in wind", k: "leaf" },
  { g: "🍎", n: "red apple", k: "apple fruit" },
  { g: "🍏", n: "green apple", k: "apple fruit" },
  { g: "🍐", n: "pear", k: "fruit" },
  { g: "🍊", n: "tangerine", k: "orange fruit" },
  { g: "🍋", n: "lemon", k: "fruit" },
  { g: "🍌", n: "banana", k: "fruit" },
  { g: "🍉", n: "watermelon", k: "fruit" },
  { g: "🍇", n: "grapes", k: "fruit" },
  { g: "🍓", n: "strawberry", k: "fruit" },
  { g: "🫐", n: "blueberries", k: "fruit" },
  { g: "🍈", n: "melon", k: "fruit" },
  { g: "🍒", n: "cherries", k: "fruit" },
  { g: "🍑", n: "peach", k: "fruit" },
  { g: "🥭", n: "mango", k: "fruit" },
  { g: "🍍", n: "pineapple", k: "fruit" },
  { g: "🥥", n: "coconut", k: "fruit" },
  { g: "🥝", n: "kiwi fruit", k: "fruit" },
  { g: "🍅", n: "tomato", k: "veg" },
  { g: "🥑", n: "avocado", k: "avocado" },
  { g: "🍆", n: "eggplant", k: "veg" },
  { g: "🥔", n: "potato", k: "veg" },
  { g: "🥕", n: "carrot", k: "veg" },
  { g: "🌽", n: "ear of corn", k: "corn" },
  { g: "🌶️", n: "hot pepper", k: "spicy" },
  { g: "🥒", n: "cucumber", k: "veg" },
  { g: "🥬", n: "leafy green", k: "salad" },
  { g: "🥦", n: "broccoli", k: "veg" },
  { g: "🧄", n: "garlic", k: "veg" },
  { g: "🧅", n: "onion", k: "veg" },
  { g: "🍞", n: "bread", k: "food" },
  { g: "🥐", n: "croissant", k: "food" },
  { g: "🥖", n: "baguette bread", k: "food" },
  { g: "🧀", n: "cheese wedge", k: "cheese" },
  { g: "🥚", n: "egg", k: "egg" },
  { g: "🍳", n: "cooking", k: "fried egg" },
  { g: "🧈", n: "butter", k: "butter" },
  { g: "🥞", n: "pancakes", k: "food" },
  { g: "🧇", n: "waffle", k: "food" },
  { g: "🥓", n: "bacon", k: "food" },
  { g: "🥩", n: "cut of meat", k: "steak" },
  { g: "🍗", n: "poultry leg", k: "chicken" },
  { g: "🍖", n: "meat on bone", k: "meat" },
  { g: "🌭", n: "hot dog", k: "food" },
  { g: "🍔", n: "hamburger", k: "burger food" },
  { g: "🍟", n: "french fries", k: "fries" },
  { g: "🍕", n: "pizza", k: "pizza food" },
  { g: "🫓", n: "flatbread", k: "food" },
  { g: "🥪", n: "sandwich", k: "food" },
  { g: "🌮", n: "taco", k: "food" },
  { g: "🌯", n: "burrito", k: "food" },
  { g: "🥗", n: "green salad", k: "salad" },
  { g: "🍝", n: "spaghetti", k: "pasta" },
  { g: "🍜", n: "steaming bowl", k: "ramen" },
  { g: "🍲", n: "pot of food", k: "stew" },
  { g: "🍛", n: "curry rice", k: "curry" },
  { g: "🍣", n: "sushi", k: "sushi" },
  { g: "🍱", n: "bento box", k: "bento" },
  { g: "🥟", n: "dumpling", k: "dumpling" },
  { g: "🍤", n: "fried shrimp", k: "shrimp" },
  { g: "🍙", n: "rice ball", k: "onigiri" },
  { g: "🍚", n: "cooked rice", k: "rice" },
  { g: "🍦", n: "soft ice cream", k: "dessert" },
  { g: "🍧", n: "shaved ice", k: "dessert" },
  { g: "🍨", n: "ice cream", k: "dessert" },
  { g: "🍩", n: "doughnut", k: "donut" },
  { g: "🍪", n: "cookie", k: "cookie" },
  { g: "🎂", n: "birthday cake", k: "cake birthday" },
  { g: "🍰", n: "shortcake", k: "cake" },
  { g: "🧁", n: "cupcake", k: "cake" },
  { g: "🍫", n: "chocolate bar", k: "chocolate" },
  { g: "🍬", n: "candy", k: "sweet" },
  { g: "🍭", n: "lollipop", k: "candy" },
  { g: "☕", n: "hot beverage", k: "coffee tea" },
  { g: "🍵", n: "teacup without handle", k: "tea" },
  { g: "🧃", n: "beverage box", k: "juice" },
  { g: "🥤", n: "cup with straw", k: "soda" },
  { g: "🍺", n: "beer mug", k: "beer drink" },
  { g: "🍻", n: "clinking beer mugs", k: "cheers beer" },
  { g: "🥂", n: "clinking glasses", k: "cheers" },
  { g: "🍷", n: "wine glass", k: "wine" },
  { g: "🥃", n: "tumbler glass", k: "whiskey" },
  { g: "🍸", n: "cocktail glass", k: "cocktail" },
  { g: "🍹", n: "tropical drink", k: "cocktail" },
  { g: "🍾", n: "bottle with popping cork", k: "champagne" },
  { g: "⚽", n: "soccer ball", k: "football soccer" },
  { g: "🏀", n: "basketball", k: "sport" },
  { g: "🏈", n: "american football", k: "sport" },
  { g: "⚾", n: "baseball", k: "sport" },
  { g: "🎾", n: "tennis", k: "sport" },
  { g: "🏐", n: "volleyball", k: "sport" },
  { g: "🏉", n: "rugby football", k: "sport" },
  { g: "🎱", n: "pool 8 ball", k: "billiards" },
  { g: "🏓", n: "ping pong", k: "sport" },
  { g: "🏸", n: "badminton", k: "sport" },
  { g: "⛳", n: "flag in hole", k: "golf" },
  { g: "🎯", n: "bullseye", k: "target" },
  { g: "🎮", n: "video game", k: "game controller" },
  { g: "🕹️", n: "joystick", k: "game" },
  { g: "🎲", n: "game die", k: "dice" },
  { g: "🧩", n: "puzzle piece", k: "puzzle" },
  { g: "♟️", n: "chess pawn", k: "chess" },
  { g: "🎸", n: "guitar", k: "music" },
  { g: "🎹", n: "musical keyboard", k: "piano" },
  { g: "🎺", n: "trumpet", k: "music" },
  { g: "🎻", n: "violin", k: "music" },
  { g: "🥁", n: "drum", k: "music" },
  { g: "🎤", n: "microphone", k: "sing" },
  { g: "🎧", n: "headphone", k: "music" },
  { g: "🎬", n: "clapper board", k: "movie" },
  { g: "🎨", n: "artist palette", k: "art" },
  { g: "📷", n: "camera", k: "photo" },
  { g: "🎥", n: "movie camera", k: "film" },
  { g: "💻", n: "laptop", k: "computer" },
  { g: "🖥️", n: "desktop computer", k: "computer" },
  { g: "⌨️", n: "keyboard", k: "type" },
  { g: "🖱️", n: "computer mouse", k: "mouse" },
  { g: "🖨️", n: "printer", k: "print" },
  { g: "📱", n: "mobile phone", k: "phone" },
  { g: "☎️", n: "telephone", k: "phone" },
  { g: "🔋", n: "battery", k: "power" },
  { g: "🔌", n: "electric plug", k: "power" },
  { g: "💡", n: "light bulb", k: "idea" },
  { g: "🔦", n: "flashlight", k: "light" },
  { g: "📡", n: "satellite antenna", k: "signal" },
  { g: "📺", n: "television", k: "tv" },
  { g: "📻", n: "radio", k: "radio" },
  { g: "⏰", n: "alarm clock", k: "time" },
  { g: "⏱️", n: "stopwatch", k: "time" },
  { g: "⏳", n: "hourglass not done", k: "wait" },
  { g: "🔒", n: "locked", k: "lock" },
  { g: "🔓", n: "unlocked", k: "unlock" },
  { g: "🔑", n: "key", k: "key" },
  { g: "🗝️", n: "old key", k: "key" },
  { g: "🔨", n: "hammer", k: "tool" },
  { g: "🛠️", n: "hammer and wrench", k: "tools" },
  { g: "⚙️", n: "gear", k: "settings" },
  { g: "🧲", n: "magnet", k: "magnet" },
  { g: "💣", n: "bomb", k: "bomb" },
  { g: "🔪", n: "kitchen knife", k: "knife" },
  { g: "🛡️", n: "shield", k: "protect" },
  { g: "🔗", n: "link", k: "url" },
  { g: "📎", n: "paperclip", k: "clip" },
  { g: "📌", n: "pushpin", k: "pin" },
  { g: "📍", n: "round pushpin", k: "location" },
  { g: "✂️", n: "scissors", k: "cut" },
  { g: "📝", n: "memo", k: "note write" },
  { g: "📁", n: "file folder", k: "folder" },
  { g: "📂", n: "open file folder", k: "folder" },
  { g: "📅", n: "calendar", k: "date" },
  { g: "📆", n: "tear-off calendar", k: "date" },
  { g: "📊", n: "bar chart", k: "stats" },
  { g: "📈", n: "chart increasing", k: "up" },
  { g: "📉", n: "chart decreasing", k: "down" },
  { g: "📧", n: "e-mail", k: "email mail" },
  { g: "📨", n: "incoming envelope", k: "mail" },
  { g: "📦", n: "package", k: "box" },
  { g: "📫", n: "closed mailbox with raised flag", k: "mail" },
  { g: "✏️", n: "pencil", k: "write" },
  { g: "✒️", n: "black nib", k: "pen" },
  { g: "🔎", n: "magnifying glass tilted right", k: "search" },
  { g: "🔍", n: "magnifying glass tilted left", k: "search" },
  { g: "🏠", n: "house", k: "home" },
  { g: "🏢", n: "office building", k: "work" },
  { g: "🏥", n: "hospital", k: "hospital" },
  { g: "🏦", n: "bank", k: "bank" },
  { g: "🏫", n: "school", k: "school" },
  { g: "🏰", n: "castle", k: "castle" },
  { g: "⛪", n: "church", k: "church" },
  { g: "🗼", n: "tokyo tower", k: "tower" },
  { g: "🗽", n: "statue of liberty", k: "nyc" },
  { g: "🚗", n: "automobile", k: "car" },
  { g: "🚕", n: "taxi", k: "cab" },
  { g: "🚌", n: "bus", k: "bus" },
  { g: "🚎", n: "trolleybus", k: "bus" },
  { g: "🏎️", n: "racing car", k: "race" },
  { g: "🚓", n: "police car", k: "police" },
  { g: "🚑", n: "ambulance", k: "emergency" },
  { g: "🚒", n: "fire engine", k: "fire" },
  { g: "🚜", n: "tractor", k: "farm" },
  { g: "🚲", n: "bicycle", k: "bike" },
  { g: "🛵", n: "motor scooter", k: "scooter" },
  { g: "🏍️", n: "motorcycle", k: "bike" },
  { g: "✈️", n: "airplane", k: "flight plane" },
  { g: "🚀", n: "rocket", k: "launch space" },
  { g: "🛸", n: "flying saucer", k: "ufo" },
  { g: "🚁", n: "helicopter", k: "heli" },
  { g: "🚂", n: "locomotive", k: "train" },
  { g: "🚆", n: "train", k: "train" },
  { g: "🚇", n: "metro", k: "subway" },
  { g: "🚉", n: "station", k: "train" },
  { g: "🚢", n: "ship", k: "boat" },
  { g: "⛵", n: "sailboat", k: "boat" },
  { g: "⚓", n: "anchor", k: "navy" },
  { g: "🗺️", n: "world map", k: "map" },
  { g: "🧭", n: "compass", k: "navigate" },
  { g: "🌍", n: "globe showing Europe-Africa", k: "earth world" },
  { g: "🌎", n: "globe showing Americas", k: "earth world" },
  { g: "🌏", n: "globe showing Asia-Australia", k: "earth world" },
  { g: "⏰", n: "alarm clock", k: "alarm" },
  { g: "🌙", n: "crescent moon", k: "night" },
  { g: "☀️", n: "sun", k: "sunny" },
  { g: "🌤️", n: "sun behind small cloud", k: "weather" },
  { g: "⛅", n: "sun behind cloud", k: "cloud" },
  { g: "🌧️", n: "cloud with rain", k: "rain" },
  { g: "⛈️", n: "cloud with lightning and rain", k: "storm" },
  { g: "🌩️", n: "cloud with lightning", k: "storm" },
  { g: "❄️", n: "snowflake", k: "snow cold" },
  { g: "☃️", n: "snowman", k: "snow" },
  { g: "⛄", n: "snowman without snow", k: "snow" },
  { g: "🌈", n: "rainbow", k: "pride" },
  { g: "☔", n: "umbrella with rain drops", k: "rain" },
  { g: "⚡", n: "high voltage", k: "zap lightning" },
  { g: "💧", n: "droplet", k: "water" },
  { g: "🌊", n: "water wave", k: "ocean" },
  { g: "🎄", n: "Christmas tree", k: "xmas" },
  { g: "🎃", n: "jack-o-lantern", k: "halloween" },
  { g: "🎁", n: "wrapped gift", k: "present" },
  { g: "🎈", n: "balloon", k: "party" },
  { g: "🎉", n: "party popper", k: "tada celebrate" },
  { g: "🎊", n: "confetti ball", k: "party" },
  { g: "🏆", n: "trophy", k: "win" },
  { g: "🥇", n: "1st place medal", k: "gold" },
  { g: "🥈", n: "2nd place medal", k: "silver" },
  { g: "🥉", n: "3rd place medal", k: "bronze" },
  { g: "🏅", n: "sports medal", k: "medal" },
  { g: "🇩🇪", n: "flag Germany", k: "germany de" },
  { g: "🇪🇺", n: "flag European Union", k: "eu europe" },
  { g: "🇺🇸", n: "flag United States", k: "usa us" },
  { g: "🇬🇧", n: "flag United Kingdom", k: "uk gb" },
  { g: "🇯🇵", n: "flag Japan", k: "japan jp" }
]

function term(query) {
  const q = String(query || "").trim()
  if (q.charAt(0) !== ";") return null
  return q.substring(1).replace(/^\s+/, "")
}

function hay(entry) {
  return (entry.n + " " + (entry.k || "") + " " + entry.g).toLowerCase()
}

function search(query, limit) {
  const cap = limit == null ? 60 : Number(limit)
  const q = String(query || "").trim().toLowerCase()
  const out = []
  const src = EMOJI
  if (!q) {
    for (let i = 0; i < src.length && out.length < cap; i++) out.push(src[i])
    return out
  }
  const tokens = q.split(/\s+/).filter(function (t) { return t.length > 0 })
  for (let i = 0; i < src.length; i++) {
    const h = hay(src[i])
    let ok = true
    for (let t = 0; t < tokens.length; t++) {
      if (h.indexOf(tokens[t]) < 0) { ok = false; break }
    }
    if (!ok) continue
    out.push(src[i])
    if (out.length >= cap) break
  }
  return out
}

function placeholder() {
  return "Type to filter emoji"
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    EMOJI: EMOJI,
    term: term,
    search: search,
    placeholder: placeholder
  }
}
