#!/usr/bin/env sh

# window rules
yabai -m rule --add app='^System Information$' manage=off border=off
yabai -m rule --add app='^System Preferences$' manage=off border=off
yabai -m rule --add title='Preferences$' manage=off border=off
yabai -m rule --add title='Settings$' manage=off border=off
yabai -m rule --add app="^(Dictionary|Music|Podcasts|App Store|Calendar|Photos)$" manage=off border=off
yabai -m rule --add app="^(Anki|Bitwarden)$" manage=off border=off

# always let PiP float around
yabai -m rule --add title="Picture in Picture" manage=off border=off
