#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config window_origin_display        default
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
# Floating windows are always on top
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config normal_window_opacity        0.9
yabai -m config active_window_opacity        0.95

yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config window_hidpi                 off
yabai -m config window_border_radius         8

yabai -m config active_window_border_color   0xff6e3b9f
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

# mouse
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off #autoraise
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# use shortcut to balance myself
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# general space settings
yabai -m config layout                       stack
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10
yabai -m config external_bar                 all:0:25

# events
yabai -m signal --add event=window_created action="sketchybar -m --trigger window_created &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_destroyed &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=display_removed action="launchctl kickstart -k \"gui/${UID}/homebrew.mxcl.yabai\""
yabai -m signal --add event=display_added action="launchctl kickstart -k \"gui/${UID}/homebrew.mxcl.yabai\""

WINDOW_RULES="$HOME/.config/yabai/window_rules"
if [[ -f $WINDOW_RULES ]]; then
  source $WINDOW_RULES
fi

echo "yabai configuration loaded..."
