FROM ubuntu:20.04

RUN apt-get -y update && apt-get install -y make cmake sudo software-properties-common curl
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y locales \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=en_US.UTF-8
COPY . /root/.dotfiles
WORKDIR /root/.dotfiles

CMD ["/bin/bash"]

# vim: set filetype=dockerfile:
