#!/usr/bin/env sh

# reload skhd and yabai
ctrl + alt + cmd - r : \
  yabai --restart-service; \
  skhd --restart-service;

# reload sketchybar
ctrl + alt + cmd - b : sketchybar --reload && sketchybar-top --reload

# toggle main terminal application
fn - space : bash "$DOTFILES/scripts/toggle_app.bash" "Ghostty"

# fn + shift - s : open "x-apple.systempreferences:"
# fn + shift - a : open -a "About This Mac"
# fn + shift - b : bash "$DOTFILES/scripts/toggle_app.bash" "$BROWSER_NAME"

# yabai scratchpads
fn + alt - m : yabai -m window --toggle music || open -a Music
fn + alt - n : yabai -m window --toggle notes || open -a Notes
fn + alt - p : yabai -m window --toggle pw || open -a "Proton Pass"

# Move space to next display
fn + alt - 1 : yabai -m space --display 1
fn + alt - 2 : yabai -m space --display 2

########
#  FN  #
########
# Most frequently used shortcuts

# # change window focus
fn - h : yabai -m window --focus west
fn - j : yabai -m window --focus south
fn - k : yabai -m window --focus north
fn - l : yabai -m window --focus east
# going stack (u)p and (d)own
fn - d : yabai -m window --focus stack.prev
fn - u : yabai -m window --focus stack.next

# change space focus
fn - y : yabai -m space --focus recent
fn - x : yabai -m space --focus prev
fn - c : yabai -m space --focus next

fn - 1 : yabai -m space --focus 1 || skhd -k "ctrl + alt + cmd - 1"
fn - 2 : yabai -m space --focus 2 || skhd -k "ctrl + alt + cmd - 2"
fn - 3 : yabai -m space --focus 3 || skhd -k "ctrl + alt + cmd - 3"
fn - 4 : yabai -m space --focus 4 || skhd -k "ctrl + alt + cmd - 4"
fn - 5 : yabai -m space --focus 5 || skhd -k "ctrl + alt + cmd - 5"
fn - 6 : yabai -m space --focus 6
fn - 7 : yabai -m space --focus 7
fn - 8 : yabai -m space --focus 8
fn - 9 : yabai -m space --focus 9

# change layout of space (i3 defaults)
fn - e : yabai -m space --layout bsp; sketchybar-top --trigger layout_change
fn - w : yabai -m space --layout float; sketchybar-top --trigger layout_change
fn - s : yabai -m space --layout stack; sketchybar-top --trigger layout_change

# quit/close focused window
fn - q : yabai -m window --close

# enter fullscreen mode for the focused container
fn - f : yabai -m window --toggle zoom-fullscreen; sketchybar-top --trigger layout_change

# toggle picture-in-picture
fn - p : yabai -m window --toggle pip

# rotate tree
fn - r : yabai -m space --rotate 90
# fn + shift - r : yabai -m space --rotate 180

###############
#  FN + CTRL  #
###############
# Shortcuts to move and open applications

# move window to space and focus
fn + ctrl - y  : yabai -m window --space recent && yabai -m space --focus recent
fn + ctrl - x  : yabai -m window --space prev && yabai -m space --focus prev
fn + ctrl - c  : yabai -m window --space next && yabai -m space --focus next

# move window to space and follow with focus
fn + ctrl - 1  : yabai -m window --space 1 && yabai -m space --focus 1
fn + ctrl - 2  : yabai -m window --space 2 && yabai -m space --focus 2
fn + ctrl - 3  : yabai -m window --space 3 && yabai -m space --focus 3
fn + ctrl - 4  : yabai -m window --space 4 && yabai -m space --focus 4
fn + ctrl - 5  : yabai -m window --space 5 && yabai -m space --focus 5
fn + ctrl - 6  : yabai -m window --space 6 && yabai -m space --focus 6
fn + ctrl - 7  : yabai -m window --space 7 && yabai -m space --focus 7
fn + ctrl - 8  : yabai -m window --space 8 && yabai -m space --focus 8
fn + ctrl - 9  : yabai -m window --space 9 && yabai -m space --focus 9

# shift window in current space, possibly also to adjacent display
fn + ctrl - h : yabai -m window --swap west || $(yabai -m window --display west; yabai -m display --focus west)
fn + ctrl - j : yabai -m window --swap south || $(yabai -m window --display south; yabai -m display --focus south)
fn + ctrl - k : yabai -m window --swap north || $(yabai -m window --display north; yabai -m display --focus north)
fn + ctrl - l : yabai -m window --swap east || $(yabai -m window --display east; yabai -m display --focus east)

# fn + ctrl - s : open "x-apple.systempreferences:"
# fn + ctrl - a : open -a "About This Mac"
# fn + ctrl - b : bash "$DOTFILES/scripts/toggle_app.bash" "$BROWSER_NAME"

################
#  FN + SHIFT  #
################

# toggle window native fullscreen
fn + shift - f : yabai -m window --toggle native-fullscreen
# toggle stickyness (show on all spaces)
fn + shift - s : yabai -m window --toggle sticky --sub-layer above; sketchybar-top --trigger property_change
# toggle float and center on screen
fn + shift - w : yabai -m window --toggle float && yabai -m window --grid 4:4:1:1:2:2; sketchybar-top --trigger property_change
# toggle window split type
fn + shift - space: yabai -m window --toggle split
# toggle desktop offset
fn + shift - d : yabai -m space --toggle padding && yabai -m space --toggle gap
# toggle window parent zoom
fn + shift - z : yabai -m window --toggle zoom-parent; sketchybar-top --trigger property_change
# mirror tree x-axis
fn + shift - x : yabai -m space --mirror x-axis
# mirror tree y-axis
fn + shift - y : yabai -m space --mirror y-axis
# balance size of windows
fn + shift - 0 : yabai -m space --balance

# move window to space
fn + shift - 1  : yabai -m window --space 1
fn + shift - 2  : yabai -m window --space 2
fn + shift - 3  : yabai -m window --space 3
fn + shift - 4  : yabai -m window --space 4
fn + shift - 5  : yabai -m window --space 5
fn + shift - 6  : yabai -m window --space 6
fn + shift - 7  : yabai -m window --space 7
fn + shift - 8  : yabai -m window --space 8
fn + shift - 9  : yabai -m window --space 9

# create space, move current window and focus
fn + shift - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}"; \
                  sketchybar-top --trigger layout_change

# create space in background
fn + shift + ctrl - n : yabai -m space --create && \
                index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                yabai -m space --focus "${index}"; \
                sketchybar-top --trigger layout_change

# destroy space
fn + shift - q : yabai -m space --destroy; sketchybar-top --trigger layout_change

#################
#  SHIFT + ALT  #
#################

# increase window size
shift + alt - h : yabai -m window --resize left:-20:0; yabai -m window --resize right:20:0
shift + alt - j : yabai -m window --resize bottom:0:20
shift + alt - k : yabai -m window --resize top:0:-20
shift + alt - l : yabai -m window --resize right:-20:0; yabai -m window --resize left:20:0

# make floating window fill screen
shift + alt - up : yabai -m window --grid 1:1:0:0:1:1
# make floating window fill left-half of screen
shift + alt - left : yabai -m window --grid 1:2:0:0:1:1
# make floating window fill right-half of screen
shift + alt - right : yabai -m window --grid 1:2:1:0:1:1
# center floating window
shift + alt - down : yabai -m window --grid 4:4:1:1:2:2
