animations {
  enabled = true

  bezier = easeOutQuint, 0.23, 1, 0.32, 1
  bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1

  animation = windowsIn, 1, 3, easeOutQuint, popin 80%
  animation = windowsOut, 1, 2, easeInOutCubic, popin 80%
  animation = windowsMove, 1, 3, easeOutQuint
  animation = fade, 1, 3, easeOutQuint
  animation = workspaces, 1, 4, easeOutQuint
}
