animations {
  enabled = true

  bezier = ilyaEase, 0.05, 0.9, 0.1, 1.05

  animation = windows, 1, 5, ilyaEase, popin 80%
  animation = layers, 1, 5, ilyaEase, fade
  animation = fade, 1, 5, ilyaEase
  animation = workspaces, 1, 5, ilyaEase, slide
  animation = specialWorkspace, 1, 5, ilyaEase, fade
}
