exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = ~/.dotfiles/asahi/autostart-scripts/ssh-keychain
exec-once = elephant service enable
exec-once = systemctl --user start elephant.service
exec-once = playerctld
exec-once = walker --gapplication-service
exec-once = hyprpaper
exec-once = swayosd-server
exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = mako --config ~/.config/mako/config
exec-once = hypridle
exec-once = hyprdynamicmonitors run
exec-once = [workspace 1 silent] $terminal
