local terminal = "ghostty"

hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE")
  hl.exec_cmd("systemctl --user start pipewire.socket pipewire-pulse.socket wireplumber.service")
  hl.exec_cmd("systemctl --user restart xdg-desktop-portal-hyprland.service xdg-desktop-portal.service")
  hl.exec_cmd("~/.dotfiles/asahi/autostart-scripts/ssh-keychain")
  hl.exec_cmd("playerctld")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("swayosd-server")
  hl.exec_cmd("qs -c remix")
  hl.exec_cmd("hypridle")
  hl.exec_cmd(terminal, { workspace = "1 silent" })
end)
