exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = ~/.dotfiles/asahi/bin/asahi-autostart
exec-once = elephant service enable
exec-once = systemctl --user start elephant.service
exec-once = ~/.dotfiles/asahi/bin/asahi-walker --gapplication-service
exec-once = hyprpaper
exec-once = ~/.dotfiles/asahi/bin/asahi-swayosd-server
exec-once = ~/.dotfiles/asahi/bin/asahi-waybar
exec-once = ~/.dotfiles/asahi/bin/asahi-mako
exec-once = hypridle
exec-once = [workspace 1 silent] $terminal
