general {
  gaps_in = 5
  gaps_out = 10
  border_size = 3
  col.active_border = $blue $mauve 45deg
  col.inactive_border = $surface1
  layout = dwindle
}

decoration {
  rounding = 10
  active_opacity = 1.0
  inactive_opacity = 0.9

  shadow {
    enabled = true
    range = 18
    render_power = 3
    color = rgba(11111baa)
  }

  blur {
    enabled = true
    size = 4
    passes = 2
    noise = 0.0117
    vibrancy = 0.1696
  }
}

dwindle {
  preserve_split = true
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  focus_on_activate = true
}
