input {
  kb_layout = de
  kb_variant = mac_nodeadkeys
  numlock_by_default = true
  repeat_delay = 300
  repeat_rate = 40
  accel_profile = flat

  touchpad {
    natural_scroll = true
    tap-to-click = true
  }
}
