windowrule = opacity 0.97 0.9, match:class .*
windowrule = float on, match:class ^(firefox|librewolf)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(zoom)$
windowrule = float on, match:class ^(blueman-manager|nm-connection-editor)$
windowrule = center on, match:class ^(blueman-manager|nm-connection-editor)$
layerrule = no_anim on, match:namespace ^(volume_osd)$
layerrule = no_anim on, match:namespace ^(brightness_osd)$
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.35, match:namespace waybar
