[config]

[templates.dmszsh]
input_path = '~/.dotfiles/asahi/matugen/templates/zsh-colors.zsh'
output_path = '~/.cache/DankMaterialShell/zsh-colors.zsh'
post_hook = 'pkill -URG -x zsh'

[templates.dmslibrewolf]
input_path = '/usr/share/quickshell/dms/matugen/templates/firefox-userchrome.css'
output_path = '~/.config/DankMaterialShell/librewolf.css'

[templates.nvim]
input_path = '/usr/share/quickshell/dms/matugen/templates/neovim.lua'
output_path = '~/.config/nvim/lua/plugins/dankcolors.lua'
post_hook = 'pkill -SIGUSR1 nvim'
