background {
  monitor =
  path = /home/froeder/Pictures/wallpaper/rocket_launch.jpg
  color = rgb(1e1e2e)
}

input-field {
  monitor =
  outline_thickness = 8
  outer_color = rgb(89b4fa)
  inner_color = rgb(313244)
  font_color = rgb(cdd6f4)
  fade_on_empty = false
  position = 0, -80
}

label {
  monitor =
  text = cmd[update:1000] date +'%H:%M'
  color = rgb(cdd6f4)
  font_size = 84
  font_family = Cascadia Mono NF
  position = 0, 80
}
