# Minimal Hyprland setup for Asahi Fedora.

$terminal = ghostty
$browser = librewolf
$launcher = walker
$mainMod = SUPER

source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/asahi.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/rules.conf
source = ~/.config/hypr/conf.d/bindings.conf
source = ~/.config/hypr/conf.d/autostart.conf
