#!/usr/bin/env zsh
# login shell definitions

if [ "$OSTYPE" = "Darwin" ]; then

  if [[ $ARCHITECTURE == 'arm64' ]]; then
    alias abrew='/opt/homebrew/bin/brew'
    eval $(/opt/homebrew/bin/brew shellenv)
  else
    eval $(/usr/local/bin/brew shellenv)
  fi
  # llvm
  path=("$HOMEBREW_PREFIX/opt/llvm/bin" $path)
  export LDFLAGS="-L$HOMEBREW_PREFIX/opt/llvm/lib $LDFLAGS"
  export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/llvm/include $CPPFLAGS"

  # for compilers to find openssl
  path=("$HOMEBREW_PREFIX/opt/openssl/bin" $path)
  export LDFLAGS="-L$HOMEBREW_PREFIX/opt/openssl/lib $LDFLAGS"
  export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/openssl/include $CPPFLAGS"

  # ruby + gem
  if [ -d "$HOME/.gem/ruby" ]; then
    path=("$HOME/.gem/ruby/"*/bin(N[-1]) $path)
  fi

  # go
  export GOPATH="$HOME/Documents/golang"
  export GOROOT="$HOMEBREW_PREFIX/opt/go/libexec"
  path=(
    $GOPATH/bin
    $GOROOT/bin
    $path
  )
fi

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  Hyprland
fi
