#!/usr/bin/env zsh

# llvm
path=("/usr/local/opt/llvm/bin" $path)
export LDFLAGS="-L/usr/local/opt/llvm/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/llvm/include $LDFLAGS"

# go
export GOPATH="$HOME/Documents/golang"
export GOROOT="/usr/local/opt/go/libexec"

BREW_PREFIX="$(brew --prefix)"

path=(
  ${BREW_PREFIX}/opt/python3/libexec/bin(N-/)
  ${HOME}/Library/Python/3.*/bin
  /usr/local/{bin,sbin}
  $DOTFILES/bin
  $GOPATH/bin
  $GOROOT/bin
  $path
)

# for compilers to find openssl
path=("/usr/local/opt/openssl/bin" $path)
export LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/openssl/include $LDFLAGS"
