#!/usr/bin/env zsh
# definitions for all sessions and scripts

export DOTFILES=$HOME/.dotfiles
export OSTYPE=$(uname -s)
export ARCHITECTURE=$(uname -m)

path=(
  # path to linux and homebrew intel-based binaries
  /usr/local/{bin,sbin}
  # os-specific dotfile binaries
  $DOTFILES/bin/$OSTYPE
  # user-specific binaries for linux
  $HOME/bin
  $path
)

[[ $ARCHITECTURE == 'arm64' ]] && {
  path=(
    # homebrew arm-based binaries
    /opt/homebrew/{bin,sbin}
    $path
  )
}

if (( ${+commands[neovide]} )); then
	export EDITOR="/Applications/Neovide.app/Contents/MacOS/neovide"
  export NEOVIDE_FRAMELESS=1
elif (( ${+commands[nvim]} )); then
  export EDITOR=$(which nvim)
elif (( ${+commands[vim]} )); then
  export EDITOR=$(which vim)
elif (( ${+commands[vi]} )); then
  export EDITOR=$(which vi)
else
  echo "No EDITOR specified"
fi
export VISUAL="${EDITOR}"
if [[ "$OSTYPE" == "Darwin" ]]; then
  export BROWSER="open"
elif [[ "$OSTYPE" == "Linux" ]]; then
  [ $commands[firefox] ] && export BROWSER="firefox"
fi
# name of the browser application for various scripts
export BROWSER_NAME="Firefox"
export BLOCKSIZE=1k

# -R  color
# -F  exit if there is less than one page of content
# -X  keep content on screen after exit
# -x2 tabs are 2 instead of 8
export LESS='-XFRx2'
export PAGER='less'
export MANPAGER='less'

export LANG=en_US.UTF-8
export LC_ALL=$LANG

export GPG_TTY=$(tty)

if [ -d "$HOME/.cargo" ]; then
  source "$HOME/.cargo/env";
fi
