#!/usr/bin/env zsh
#
export DOTFILES=$HOME/.dotfiles

if [[ -f "$(command -v /usr/local/bin/nvim)" ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vi'
fi

export VISUAL=$EDITOR
export BROWSER=/Applications/Safari.app
export BLOCKSIZE=1k
export CLICOLOR=true
autoload -U colors && colors

export LESS='-XFR'
export PAGER='less'
export MANPAGER='less -X'

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export GPG_TTY=$(tty)
