#!/usr/bin/env zsh

export DOTFILES=$HOME/.dotfiles
export OSTYPE=$(uname -s)
if (( ${+commands[nvim]} )); then
    export EDITOR="nvim"
elif (( ${+commands[vim]} )); then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi
export VISUAL="${EDITOR}"
export BROWSER="open"
export BLOCKSIZE=1k

# -R  color
# -F  exit if there is less than one page of content
# -X  keep content on screen after exit
# -x2 tabs are 2 instead of 8
export LESS='-XFRx2'
export PAGER='less'
export MANPAGER='less'

export LANG=en_US.UTF-8
export LC_ALL=$LANG

export GPG_TTY=$(tty)
