# Path to your dotfiles installation.
export DOTFILES=$HOME/.dotfiles

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export PLATFORM=$(uname -s)

ZSH_THEME="spaceship"

CASE_SENSITIVE=true

DISABLE_AUTO_TITLE=true
DISABLE_AUTO_UPDATE=true

HIST_STAMPS="dd.mm.yyyy"

[ -f ~/.local.zsh ] && source ~/.local.zsh

ZSH_CUSTOM=$DOTFILES/zsh/dots/

plugins=(
  docker
  extract
  fzf
  git
  tmux
  zsh_reload
)

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

ZSH_TMUX_AUTOSTART='true'

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source $DOTFILES/ssh-find-agent/ssh-find-agent.sh
set_ssh_agent_socket

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# remove color-inverter % when output doesn't include trailing newline
unsetopt prompt_cr prompt_sp

# source fuzzy file search - fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# ssh-agent and keys
source "$DOTFILES/bin/start-ssh-agent"

eval "`pip completion --zsh`"

# gcloud
if type gcloud &>/dev/null; then
  local GCPREFIX='/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk'
  source $GCPREFIX'/path.zsh.inc'
  source $GCPREFIX'/completion.zsh.inc'
fi

if type terraform &>/dev/null; then
  TF_VERSION=$(terraform --version | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')
  complete -o nospace -C "$(brew --prefix)/Cellar/terraform/$TF_VERSION/bin/terraform" terraform
fi
