#!/usr/bin/env zsh
# definitions for all interactive sessions

# Uncomment to profile zsh
# zmodload zsh/zprof

# ensure to only execute on ZSH
[ ! -n "$ZSH_VERSION" ] && return

# autoloaded functions (lazy loading)
zsh_functions=$DOTFILES/autoloaded
fpath=($zsh_functions $fpath)

if [[ -d "$zsh_functions" ]]; then
  for func in $zsh_functions/*; do
    autoload -Uz ${func:t}
  done
  unset func
fi
unset zsh_functions

# plugin manager
ZIM_CONFIG_FILE=$DOTFILES/zsh/zimrc
ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi
# Install missing modules and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
  source ${ZIM_HOME}/zimfw.zsh init
fi
# Initialize modules.
source ${ZIM_HOME}/init.zsh

# Disable paste highlighting
zle_highlight+=(paste:none)

if [[ -d "$HOME/.fzf/bin" ]]; then
  path=($HOME/.fzf/bin $path)
fi
if (( ${+commands[fzf]} )); then
  eval "$(fzf --zsh)"
fi

# Source shared configurations (used by both bash and zsh)
if [[ -d "$DOTFILES/shared" ]]; then
  for file in $DOTFILES/shared/*.sh; do
    source $file
  done
  unset file
fi

[ -f ~/.local.zsh ] && source ~/.local.zsh

# load zsh-specific configs
zsh_dots=$DOTFILES/zsh/dots
if [[ -d "$zsh_dots" ]]; then
  [[ -r "$zsh_dots/completion.zsh" ]] && source "$zsh_dots/completion.zsh"
  for file in $zsh_dots/*.zsh; do
    [[ ${file:t} == "completion.zsh" ]] && continue
    source $file
  done
  unset file
fi
unset zsh_dots

# Prevent duplicates in PATH and FPATH
typeset -U path fpath
export PATH

if [[ "$OSTYPE" == "Darwin" ]]; then
  if ( which zprof > /dev/null ); then
    zprof | less
  fi
fi
