# Path to your dotfiles installation.
export DOTFILES=$HOME/.dotfiles

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export PLATFORM=$(uname -s)

ZSH_THEME="spaceship"
# ZSH_THEME="ys"

SPACESHIP_PROMPT_DEFAULT_PREFIX=""
SPACESHIP_USER_SHOW=false

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_COLOR="white"

SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_COLOR="yellow"
SPACESHIP_DIR_TRUNC_REPO=false

SPACESHIP_BATTERY_THRESHOLD="20"

SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_SYMBOL=""
SPACESHIP_GIT_BRANCH_SUFFIX=""
SPACESHIP_GIT_BRANCH_COLOR="green"

SPACESHIP_DOCKER_PREFIX=""
SPACESHIP_DOCKER_COLOR="blue"
SPACESHIP_DOCKER_SYMBOL="🐳  "

SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_VENV_SYMBOL="🐍  "

SPACESHIP_KUBECONTEXT_PREFIX=""
SPACESHIP_KUBECONTEXT_SHOW=true

CASE_SENSITIVE="true"

DISABLE_AUTO_TITLE="true"

HIST_STAMPS="dd.mm.yyyy"

[ -f ~/.local.zsh ] && source ~/.local.zsh

ZSH_CUSTOM=$DOTFILES/zsh/dots/

plugins=(
  docker
  extract
  fzf
  git
  tmux
  zsh_reload
)
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

ZSH_TMUX_AUTOSTART='true'

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source $DOTFILES/ssh-find-agent/ssh-find-agent.sh
set_ssh_agent_socket

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# remove color-inverter % when output doesn't include trailing newline
unsetopt prompt_cr prompt_sp

test -e "${HOME}/.iterm2_shell_integration.zsh" && \
  source "${HOME}/.iterm2_shell_integration.zsh"

# source fuzzy file search - fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# ssh-agent and keys
source "$DOTFILES/bin/start-ssh-agent"

eval "`pip completion --zsh`"

# gcloud
if type gcloud &>/dev/null; then
  local GCPREFIX='/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk'
  source $GCPREFIX'/path.zsh.inc'
  source $GCPREFIX'/completion.zsh.inc'
fi
