#!/usr/bin/env bash
if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM='xterm-256color';
fi

# Automatically trim long paths in the prompt (requires Bash 4.x)
# PROMPT_DIRTRIM=2

get_git_repository_details() {

    local branchName=""
    local tmp=""
    # Check if the current directory is in a Git repository.
    ! git rev-parse &>/dev/null \
        && return

    # Check if in `.git/` directory (some of the following
    # checks don't make sense/won't work in the `.git` directory).
    [ "$(git rev-parse --is-inside-git-dir)" == "true" ] \
        && return

    # Check for uncommitted changes in the index.
    if ! git diff --quiet --ignore-submodules --cached; then
        tmp="$tmp+";
    fi

    # Check for unstaged changes.
    if ! git diff-files --quiet --ignore-submodules --; then
        tmp="$tmp!";
    fi

    # Check for untracked files.
    if [ -n "$(git ls-files --others --exclude-standard)" ]; then
        tmp="$tmp?";
    fi

    # Check for stashed files.
    if git rev-parse --verify refs/stash &>/dev/null; then
        tmp="$tmp$";
    fi

    [ -n "$tmp" ] \
        && tmp=" [$tmp]"

    branchName="$( printf "%s" "$( git rev-parse --abbrev-ref HEAD 2> /dev/null \
        || git rev-parse --short HEAD 2> /dev/null \
        || printf " (unknown)" )" | tr -d "\n" )"

    printf "%s" " $1$branchName$tmp"
}

RED=$'\e[0;31m'
GREEN=$'\e[0;32m'
YELLOW=$'\e[0;33m'
BLUE=$'\e[0;34m'
WHITE=$'\e[1;37m'
BLACK=$'\e[0;30m'
PURPLE=$'\e[0;35m'
CYAN=$'\e[0;36m'
GRAY=$'\e[1;30m'
PINK=$'\e[37;1;35m'
ORANGE=$'\e[91m'

RESET=$'\e[00m'

LIGHT_BLUE=$'\e[1;34m'
LIGHT_GREEN=$'\e[1;32m'
LIGHT_CYAN=$'\e[1;36m'
LIGHT_RED=$'\e[1;31m'
LIGHT_PURPLE=$'\e[1;35m'
LIGHT_YELLOW=$'\e[1;33m'
LIGHT_GRAY=$'\e[0;37m'

# Highlight when logged in as root
if [[ "${USER}" == "root" ]]; then
	userColor="${RED}";
else
	userColor="${LIGHT_BLUE}";
fi;

# Set terminal prompt
PS1="\[${userColor}\]\u";               # username
PS1+="\[${WHITE}\]@"; 
PS1+="\[${RED}\]\h";                    # host
PS1+="\[${WHITE}\]:\A ";                # time
PS1+="\[${BLUE}\]\w";                   # working directory full path
PS1+="\[${GREEN}\]";
PS1+="\$(get_git_repository_details)";  # git branch
PS1+="\n";
PS1+="\[${WHITE}\]$ ";
export PS1;

PS2="\[${YELLOW}\]→ \[${RESET}\]";
export PS2;
