#!/usr/bin/env bash
# Bash-specific aliases (common aliases are in shared/aliases.sh)

alias {src,refresh}="source ~/.bash_profile"
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias l='ls -lah'
  alias ll='ls -la'
  alias la='ls -a'
  alias l.='ls -d .*'
  alias lsd='ls -l | grep "^d"'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias venv='source ./venv/bin/activate'
alias vimrc="vim ~/.vimrc"
alias vimup="vim +PlugUpdate +qall && vim +PlugUpgrade +qall"
alias localrc="vim ~/.bash_local"

alias varwww='cd /var/www/html/'
alias distro='cat /etc/issue'

alias v0="vim -c \"normal '0\""
alias wgpu='watch -n 0.1 -d nvidia-smi'
alias whou='who -u | sort -k 3 --reverse'
